// AUTO-GENERATED by tmp-i18n/assemble-pages.ts — do not edit by hand.
// zh source of truth: glossary.ts / integrations.data.ts / models.yaml + the
// page markdown. Covers the 3 data-driven pages (glossary / integrations / models).

export type Locale = 'en' | 'ja' | 'ko' | 'es' | 'fr'

export interface GlossaryGroupTr { title: string; desc: string }
export interface GlossaryPageTr {
  frontmatter: { title: string; description: string }
  ui: {
    eyebrow: string; title: string; ledePrefix: string; ledeSuffix: string
    navAria: string; see: string; tipTitle: string; tipBody: string; tipLink: string
  }
  groups: Record<string, GlossaryGroupTr>
}

export interface IntegrationItemTr { name: string; desc: string; tag: string | null }
export interface IntegrationCatTr { id: string; title: string; lede: string; items: IntegrationItemTr[] }
export interface IntegrationsPageTr {
  frontmatter: { title: string; description: string }
  ui: {
    eyebrow: string; title: string; lede: string; calloutTitle: string; calloutBody: string
    catEyebrow: string; nextTitle: string; next: string[]
  }
  categories: IntegrationCatTr[]
}

export interface ModelsTableTr {
  headers: { model: string; context: string; price: string; status: string; tags: string }
  status: Record<string, string>
  vendorNames: Record<string, string>
  taglines: Record<string, string>
  tags: Record<string, string>
}

export const glossaryPageTr: Record<Locale, GlossaryPageTr> = {
  "en": {
    "frontmatter": {
      "title": "Glossary",
      "description": "Complete explanations of key terms from the Lurus product docs, grouped by topic."
    },
    "ui": {
      "eyebrow": "Glossary",
      "title": "Glossary",
      "ledePrefix": "Key terms from the Lurus product docs — ",
      "ledeSuffix": " entries, grouped by topic. Use Ctrl + F to jump quickly.",
      "navAria": "Jump by topic",
      "see": "Read details →",
      "tipTitle": "Missing a term?",
      "tipBody": "If a term is missing or needs more detail, feel free to open an Issue.",
      "tipLink": "GitHub Issues ↗"
    },
    "groups": {
      "general": {
        "title": "General",
        "desc": "Concepts shared across products, API, and infrastructure"
      },
      "auth": {
        "title": "Authentication",
        "desc": "Login, Token, SSO, and compliance"
      },
      "kova": {
        "title": "Kova Execution Engine",
        "desc": "Agents, WAL, MCP, and scheduling"
      },
      "memx": {
        "title": "MemX Memory",
        "desc": "Distillation, deduplication, decay, retrieval"
      },
      "lucrum": {
        "title": "Lucrum Quant",
        "desc": "Backtesting, risk metrics, trading rules"
      },
      "switch": {
        "title": "Switch Management",
        "desc": "CLI, Provider, MCP orchestration"
      },
      "lumen": {
        "title": "Lumen Observability",
        "desc": "Replay, Checkpoint, cost"
      }
    }
  },
  "ja": {
    "frontmatter": {
      "title": "用語集",
      "description": "Lurus 製品ドキュメントに登場する主要用語をテーマ別に分類した完全な解説。"
    },
    "ui": {
      "eyebrow": "用語集",
      "title": "用語集",
      "ledePrefix": "Lurus 製品ドキュメントに登場する主要用語、全 ",
      "ledeSuffix": " 件をテーマ別に分類。Ctrl + F で素早く検索できます。",
      "navAria": "テーマへ移動",
      "see": "詳細を読む →",
      "tipTitle": "用語が見つかりませんか？",
      "tipBody": "不足している、または追加が必要な用語は Issue でお知らせください。",
      "tipLink": "GitHub Issues ↗"
    },
    "groups": {
      "general": {
        "title": "共通",
        "desc": "製品・API・インフラ横断の共通概念"
      },
      "auth": {
        "title": "認証",
        "desc": "ログイン、Token、SSO、コンプライアンス関連"
      },
      "kova": {
        "title": "Kova 実行エンジン",
        "desc": "Agent、WAL、MCP とスケジューリング"
      },
      "memx": {
        "title": "MemX メモリ",
        "desc": "蒸留、重複排除、減衰、検索"
      },
      "lucrum": {
        "title": "Lucrum クオンツ",
        "desc": "バックテスト、リスク指標、取引ルール"
      },
      "switch": {
        "title": "Switch 管理",
        "desc": "CLI、Provider、MCP 連携"
      },
      "lumen": {
        "title": "Lumen オブザーバビリティ",
        "desc": "Replay、Checkpoint、コスト"
      }
    }
  },
  "ko": {
    "frontmatter": {
      "title": "용어집",
      "description": "Lurus 제품 문서에 등장하는 핵심 용어를 주제별로 묶어 정리한 완전한 설명입니다."
    },
    "ui": {
      "eyebrow": "용어집",
      "title": "용어집",
      "ledePrefix": "Lurus 제품 문서에 등장하는 핵심 용어, 총 ",
      "ledeSuffix": " 개를 주제별로 분류했습니다. Ctrl + F 로 빠르게 찾을 수 있습니다.",
      "navAria": "주제별 이동",
      "see": "자세히 보기 →",
      "tipTitle": "용어가 빠졌나요?",
      "tipBody": "누락되었거나 보완이 필요한 용어는 Issue 로 제출해 주세요.",
      "tipLink": "GitHub Issues ↗"
    },
    "groups": {
      "general": {
        "title": "공통",
        "desc": "제품·API·인프라 전반에 공통되는 개념"
      },
      "auth": {
        "title": "신원 인증",
        "desc": "로그인, Token, SSO, 컴플라이언스 관련"
      },
      "kova": {
        "title": "Kova 실행 엔진",
        "desc": "Agent, WAL, MCP 및 스케줄링"
      },
      "memx": {
        "title": "MemX 메모리",
        "desc": "증류, 중복 제거, 감쇠, 검색"
      },
      "lucrum": {
        "title": "Lucrum 퀀트",
        "desc": "백테스트, 리스크 지표, 거래 규칙"
      },
      "switch": {
        "title": "Switch 관리",
        "desc": "CLI, Provider, MCP 연동"
      },
      "lumen": {
        "title": "Lumen 옵저버빌리티",
        "desc": "Replay, Checkpoint, 비용"
      }
    }
  },
  "es": {
    "frontmatter": {
      "title": "Glosario",
      "description": "Explicación completa de los términos clave que aparecen en la documentación de productos Lurus, agrupados por tema."
    },
    "ui": {
      "eyebrow": "Glosario",
      "title": "Glosario",
      "ledePrefix": "Términos clave que aparecen en la documentación de productos Lurus, en total ",
      "ledeSuffix": " entradas, agrupadas por tema. Usa Ctrl + F para localizar rápidamente.",
      "navAria": "Saltar por tema",
      "see": "Leer detalles →",
      "tipTitle": "¿Falta algún término?",
      "tipBody": "Si falta algún término o necesita ampliarse, no dudes en abrir un Issue.",
      "tipLink": "GitHub Issues ↗"
    },
    "groups": {
      "general": {
        "title": "General",
        "desc": "Conceptos comunes a productos, API e infraestructura"
      },
      "auth": {
        "title": "Autenticación",
        "desc": "Inicio de sesión, Token, SSO y cumplimiento"
      },
      "kova": {
        "title": "Motor de ejecución Kova",
        "desc": "Agentes, WAL, MCP y planificación"
      },
      "memx": {
        "title": "Memoria MemX",
        "desc": "Destilación, deduplicación, decaimiento y recuperación"
      },
      "lucrum": {
        "title": "Lucrum cuantitativo",
        "desc": "Backtesting, métricas de control de riesgo y reglas de trading"
      },
      "switch": {
        "title": "Gestión con Switch",
        "desc": "CLI, Provider y coordinación de MCP"
      },
      "lumen": {
        "title": "Observabilidad Lumen",
        "desc": "Replay, Checkpoint y costes"
      }
    }
  },
  "fr": {
    "frontmatter": {
      "title": "Glossaire",
      "description": "Explication complète des termes clés de la documentation produit Lurus, regroupés par thème."
    },
    "ui": {
      "eyebrow": "Glossaire",
      "title": "Glossaire",
      "ledePrefix": "Termes clés de la documentation produit Lurus, soit ",
      "ledeSuffix": " entrées, regroupées par thème. Utilisez Ctrl + F pour une recherche rapide.",
      "navAria": "Aller à un thème",
      "see": "Lire le détail →",
      "tipTitle": "Un terme manquant ?",
      "tipBody": "Pour tout terme manquant ou à compléter, n'hésitez pas à ouvrir une Issue.",
      "tipLink": "GitHub Issues ↗"
    },
    "groups": {
      "general": {
        "title": "Général",
        "desc": "Concepts communs aux produits, à l'API et à l'infrastructure"
      },
      "auth": {
        "title": "Authentification",
        "desc": "Connexion, Token, SSO et conformité"
      },
      "kova": {
        "title": "Moteur d'exécution Kova",
        "desc": "Agent, WAL, MCP et ordonnancement"
      },
      "memx": {
        "title": "Mémoire MemX",
        "desc": "Distillation, déduplication, dégradation et recherche"
      },
      "lucrum": {
        "title": "Quant Lucrum",
        "desc": "Backtest, indicateurs de gestion des risques et règles de trading"
      },
      "switch": {
        "title": "Gestion Switch",
        "desc": "CLI, Provider et coordination MCP"
      },
      "lumen": {
        "title": "Observabilité Lumen",
        "desc": "Replay, Checkpoint et coûts"
      }
    }
  }
}

export const integrationsPageTr: Record<Locale, IntegrationsPageTr> = {
  "en": {
    "frontmatter": {
      "title": "Integrations & MCP Directory",
      "description": "An overview of MCP servers, Switch built-in tools, AI clients, and SDK/protocol compatibility across all Lurus products — browse by category to get connected."
    },
    "ui": {
      "eyebrow": "Integrations Directory",
      "title": "Integrations & MCP Directory",
      "lede": "Browse by category: Lurus product MCP, Switch built-in servers, AI clients, SDKs, and protocol compatibility. Each card links straight to its integration docs.",
      "calloutTitle": "This page is data-driven",
      "calloutBody": "The directory comes from a maintained data file — edit it and rebuild to sync. Every entry maps to a real, delivered capability.",
      "catEyebrow": "Integration Categories",
      "nextTitle": "Next Steps",
      "next": [
        "Switch — Unified MCP Management",
        "Data Structures / Schema",
        "Quickstart",
        "Client Integration"
      ]
    },
    "categories": [
      {
        "id": "product-mcp",
        "title": "Lurus Product MCP",
        "lede": "Lurus's own products expose their capabilities as agent tools via MCP servers, callable from MCP clients like Claude / Codex.",
        "items": [
          {
            "name": "Kova",
            "desc": "The agent execution engine exposed as an MCP tool (kova mcp serve), letting Claude/Codex drive persistent agents directly.",
            "tag": "MCP"
          },
          {
            "name": "MemX",
            "desc": "Memory read/write as agent tools: memory_add / memory_search / memory_delete, with parameters aligned to the REST API.",
            "tag": "MCP"
          },
          {
            "name": "Lumen",
            "desc": "Trace / Replay exposed to agents — debugging and zero-cost replay callable from MCP clients.",
            "tag": "MCP"
          }
        ]
      },
      {
        "id": "switch-builtin",
        "title": "Switch Built-in MCP Servers",
        "lede": "The Switch desktop app offers one-click installation of common MCP servers, delivered dynamically across CLIs by visible_to.",
        "items": [
          {
            "name": "GitHub",
            "desc": "Read/write issues / PRs / files.",
            "tag": "Built-in"
          },
          {
            "name": "PostgreSQL",
            "desc": "Query databases.",
            "tag": "Built-in"
          },
          {
            "name": "Filesystem",
            "desc": "Read/write local files.",
            "tag": "Built-in"
          },
          {
            "name": "Slack",
            "desc": "Send messages / read channels.",
            "tag": "Built-in"
          }
        ]
      },
      {
        "id": "ai-clients",
        "title": "AI Clients",
        "lede": "Just fill in the base_url and API Key to start chatting — no code required. See each client's integration guide for full steps.",
        "items": [
          {
            "name": "Cherry Studio",
            "desc": "Desktop multi-model client — fill in base_url + Key and go.",
            "tag": null
          },
          {
            "name": "Lobe Chat",
            "desc": "Open-source web / desktop chat UI with custom OpenAI-compatible endpoints.",
            "tag": null
          },
          {
            "name": "OpenCat",
            "desc": "Native iOS / macOS client with a custom API domain.",
            "tag": null
          },
          {
            "name": "Other Clients",
            "desc": "General config for any OpenAI-compatible client such as NextChat / ChatBox.",
            "tag": null
          }
        ]
      },
      {
        "id": "sdk-protocol",
        "title": "SDKs & Ecosystem Protocols",
        "lede": "Compatible with standard SDKs and protocols — migrate existing code by changing a single base_url line.",
        "items": [
          {
            "name": "OpenAI SDK",
            "desc": "Fully compatible with Python / Node.js / Go — just change base_url and api_key.",
            "tag": "SDK"
          },
          {
            "name": "LangGraph",
            "desc": "LumenCheckpointer drops in for SqliteSaver, connecting to Kova persistence.",
            "tag": null
          },
          {
            "name": "OpenTelemetry",
            "desc": "Lumen exports traces via OTLP to Grafana Tempo / Datadog APM.",
            "tag": null
          },
          {
            "name": "OIDC / OAuth2",
            "desc": "Unified identity federation with enterprise IdPs via standard OIDC / OAuth2 integration.",
            "tag": null
          }
        ]
      }
    ]
  },
  "ja": {
    "frontmatter": {
      "title": "連携と MCP カタログ",
      "description": "Lurus 全製品の MCP サーバー、Switch 内蔵ツール、AI クライアント、SDK/プロトコル互換の一覧。カテゴリ別に参照してそのまま接続できます。"
    },
    "ui": {
      "eyebrow": "連携カタログ",
      "title": "連携と MCP カタログ",
      "lede": "カテゴリ別に参照：Lurus 製品 MCP、Switch 内蔵サーバー、AI クライアント、SDK とプロトコル互換。各カードから接続ドキュメントへ直接アクセスできます。",
      "calloutTitle": "このページはデータ駆動です",
      "calloutBody": "カタログはメンテナンス中のデータファイルから生成され、編集後の再ビルドで同期されます。すべての項目は実際に提供済みの機能に対応しています。",
      "catEyebrow": "連携カテゴリ",
      "nextTitle": "次のステップ",
      "next": [
        "Switch — MCP を一元管理",
        "データ構造 / Schema",
        "クイックスタート",
        "クライアント連携"
      ]
    },
    "categories": [
      {
        "id": "product-mcp",
        "title": "Lurus 製品 MCP",
        "lede": "Lurus 自社製品は MCP server 形態で機能を agent ツールとして公開し、Claude / Codex などの MCP クライアントから呼び出せます。",
        "items": [
          {
            "name": "Kova",
            "desc": "Agent 実行エンジンを MCP ツールとして公開（kova mcp serve）。Claude/Codex から永続化 Agent を直接駆動できます。",
            "tag": "MCP"
          },
          {
            "name": "MemX",
            "desc": "メモリの読み書きを agent ツールとして公開：memory_add / memory_search / memory_delete。パラメータは REST と整合。",
            "tag": "MCP"
          },
          {
            "name": "Lumen",
            "desc": "Trace / Replay を agent に公開。デバッグとゼロコストの再生を MCP クライアントから呼び出せます。",
            "tag": "MCP"
          }
        ]
      },
      {
        "id": "switch-builtin",
        "title": "Switch 内蔵 MCP サーバー",
        "lede": "Switch デスクトップ版はワンクリックでインストールできる定番 MCP サーバーを提供し、visible_to に応じて CLI 横断で動的に配信します。",
        "items": [
          {
            "name": "GitHub",
            "desc": "issues / PR / file の読み書き。",
            "tag": "内蔵"
          },
          {
            "name": "PostgreSQL",
            "desc": "データベースのクエリ。",
            "tag": "内蔵"
          },
          {
            "name": "Filesystem",
            "desc": "ローカルファイルの読み書き。",
            "tag": "内蔵"
          },
          {
            "name": "Slack",
            "desc": "メッセージ送信 / チャンネル閲覧。",
            "tag": "内蔵"
          }
        ]
      },
      {
        "id": "ai-clients",
        "title": "AI クライアント",
        "lede": "base_url と API Key を入力するだけで対話でき、コードを書く必要はありません。詳細な手順は各クライアントの接続ガイドを参照。",
        "items": [
          {
            "name": "Cherry Studio",
            "desc": "デスクトップ向けマルチモデルクライアント。base_url + Key を入力すればすぐ利用可能。",
            "tag": null
          },
          {
            "name": "Lobe Chat",
            "desc": "オープンソースの Web / デスクトップ対話 UI。OpenAI 互換エンドポイントをカスタマイズ可能。",
            "tag": null
          },
          {
            "name": "OpenCat",
            "desc": "iOS / macOS ネイティブクライアント。API ドメインをカスタマイズして接続。",
            "tag": null
          },
          {
            "name": "その他のクライアント",
            "desc": "NextChat / ChatBox など、あらゆる OpenAI 互換クライアントの汎用設定。",
            "tag": null
          }
        ]
      },
      {
        "id": "sdk-protocol",
        "title": "SDK とエコシステムプロトコル",
        "lede": "標準的な SDK とプロトコルに互換。既存コードは base_url を 1 行変えるだけで移行できます。",
        "items": [
          {
            "name": "OpenAI SDK",
            "desc": "Python / Node.js / Go に完全互換。base_url と api_key を変更するだけ。",
            "tag": "SDK"
          },
          {
            "name": "LangGraph",
            "desc": "LumenCheckpointer で SqliteSaver を直接置き換え、Kova の永続化に接続。",
            "tag": null
          },
          {
            "name": "OpenTelemetry",
            "desc": "Lumen は OTLP で Trace を Grafana Tempo / Datadog APM へエクスポート。",
            "tag": null
          },
          {
            "name": "OIDC / OAuth2",
            "desc": "統一 ID フェデレーションで企業 IdP と連携。標準的な OIDC / OAuth2 統合。",
            "tag": null
          }
        ]
      }
    ]
  },
  "ko": {
    "frontmatter": {
      "title": "통합 및 MCP 디렉터리",
      "description": "Lurus 전 제품의 MCP 서버, Switch 내장 도구, AI 클라이언트, SDK/프로토콜 호환을 한눈에 보고 카테고리별로 둘러보며 바로 연동할 수 있습니다."
    },
    "ui": {
      "eyebrow": "통합 디렉터리",
      "title": "통합 및 MCP 디렉터리",
      "lede": "카테고리별로 둘러보세요: Lurus 제품 MCP, Switch 내장 서버, AI 클라이언트, SDK 및 프로토콜 호환. 각 카드에서 연동 문서로 바로 이동합니다.",
      "calloutTitle": "이 페이지는 데이터 기반입니다",
      "calloutBody": "디렉터리는 유지관리 중인 데이터 파일에서 가져오며, 편집 후 재빌드하면 동기화됩니다. 모든 항목은 실제로 제공되는 기능에 대응합니다.",
      "catEyebrow": "통합 분류",
      "nextTitle": "다음 단계",
      "next": [
        "Switch — MCP 통합 관리",
        "데이터 구조 / Schema",
        "빠른 시작",
        "클라이언트 통합"
      ]
    },
    "categories": [
      {
        "id": "product-mcp",
        "title": "Lurus 제품 MCP",
        "lede": "Lurus 자체 제품은 MCP server 형태로 기능을 agent 도구로 노출하여 Claude / Codex 등 MCP 클라이언트가 호출할 수 있게 합니다.",
        "items": [
          {
            "name": "Kova",
            "desc": "Agent 실행 엔진을 MCP 도구로 노출(kova mcp serve)하여 Claude/Codex 가 영속화된 Agent 를 직접 구동합니다.",
            "tag": "MCP"
          },
          {
            "name": "MemX",
            "desc": "메모리 읽기/쓰기를 agent 도구로: memory_add / memory_search / memory_delete, 파라미터는 REST 와 일치합니다.",
            "tag": "MCP"
          },
          {
            "name": "Lumen",
            "desc": "Trace / Replay 를 agent 에 노출하여 디버깅과 무비용 재생을 MCP 클라이언트가 호출할 수 있습니다.",
            "tag": "MCP"
          }
        ]
      },
      {
        "id": "switch-builtin",
        "title": "Switch 내장 MCP 서버",
        "lede": "Switch 데스크톱은 원클릭으로 설치하는 자주 쓰는 MCP 서버를 제공하며, visible_to 에 따라 CLI 간 동적으로 배포합니다.",
        "items": [
          {
            "name": "GitHub",
            "desc": "issues / PR / file 읽기·쓰기.",
            "tag": "내장"
          },
          {
            "name": "PostgreSQL",
            "desc": "데이터베이스 쿼리.",
            "tag": "내장"
          },
          {
            "name": "Filesystem",
            "desc": "로컬 파일 읽기·쓰기.",
            "tag": "내장"
          },
          {
            "name": "Slack",
            "desc": "메시지 전송 / 채널 읽기.",
            "tag": "내장"
          }
        ]
      },
      {
        "id": "ai-clients",
        "title": "AI 클라이언트",
        "lede": "base_url 과 API Key 만 입력하면 코드 작성 없이 바로 대화할 수 있습니다. 자세한 절차는 각 클라이언트 연동 가이드를 참고하세요.",
        "items": [
          {
            "name": "Cherry Studio",
            "desc": "데스크톱 멀티모델 클라이언트, base_url + Key 입력으로 바로 사용.",
            "tag": null
          },
          {
            "name": "Lobe Chat",
            "desc": "오픈소스 Web / 데스크톱 대화 UI, OpenAI 호환 엔드포인트 커스터마이즈.",
            "tag": null
          },
          {
            "name": "OpenCat",
            "desc": "iOS / macOS 네이티브 클라이언트, API 도메인 커스터마이즈로 연동.",
            "tag": null
          },
          {
            "name": "기타 클라이언트",
            "desc": "NextChat / ChatBox 등 모든 OpenAI 호환 클라이언트의 공통 설정.",
            "tag": null
          }
        ]
      },
      {
        "id": "sdk-protocol",
        "title": "SDK 및 생태계 프로토콜",
        "lede": "표준 SDK 및 프로토콜과 호환되어 기존 코드는 base_url 한 줄만 바꾸면 마이그레이션됩니다.",
        "items": [
          {
            "name": "OpenAI SDK",
            "desc": "Python / Node.js / Go 전부 호환, base_url 과 api_key 만 변경.",
            "tag": "SDK"
          },
          {
            "name": "LangGraph",
            "desc": "LumenCheckpointer 로 SqliteSaver 를 바로 교체하여 Kova 영속화에 연결.",
            "tag": null
          },
          {
            "name": "OpenTelemetry",
            "desc": "Lumen 이 OTLP 로 Trace 를 Grafana Tempo / Datadog APM 에 내보냅니다.",
            "tag": null
          },
          {
            "name": "OIDC / OAuth2",
            "desc": "기업 IdP 와 신원 페더레이션 통합, 표준 OIDC / OAuth2 연동.",
            "tag": null
          }
        ]
      }
    ]
  },
  "es": {
    "frontmatter": {
      "title": "Catálogo de integraciones y MCP",
      "description": "Panorama completo de servidores MCP, herramientas integradas de Switch, clientes de IA y compatibilidad con SDK/protocolos de todos los productos Lurus; explora por categoría y conéctate."
    },
    "ui": {
      "eyebrow": "Catálogo de integraciones",
      "title": "Catálogo de integraciones y MCP",
      "lede": "Explora por categoría: MCP de productos Lurus, servidores integrados de Switch, clientes de IA, SDK y compatibilidad con protocolos. Cada tarjeta enlaza directamente a la documentación de conexión.",
      "calloutTitle": "Esta página está basada en datos",
      "calloutBody": "El catálogo procede de un archivo de datos en mantenimiento; tras editarlo y reconstruir se sincroniza. Todas las entradas corresponden a capacidades reales ya entregadas.",
      "catEyebrow": "Categorías de integración",
      "nextTitle": "Siguiente paso",
      "next": [
        "Switch — gestión unificada de MCP",
        "Estructuras de datos / Schema",
        "Inicio rápido",
        "Integración de clientes"
      ]
    },
    "categories": [
      {
        "id": "product-mcp",
        "title": "MCP de productos Lurus",
        "lede": "Los productos propios de Lurus exponen sus capacidades como herramientas de agente en forma de servidor MCP, invocables por clientes MCP como Claude / Codex.",
        "items": [
          {
            "name": "Kova",
            "desc": "El motor de ejecución de agentes se expone como herramienta MCP (kova mcp serve), permitiendo que Claude/Codex controlen directamente agentes persistentes.",
            "tag": "MCP"
          },
          {
            "name": "MemX",
            "desc": "Lectura y escritura de memoria como herramientas de agente: memory_add / memory_search / memory_delete, con parámetros alineados con la REST.",
            "tag": "MCP"
          },
          {
            "name": "Lumen",
            "desc": "Trace / Replay expuestos al agente; la depuración y el replay sin coste pueden ser invocados por clientes MCP.",
            "tag": "MCP"
          }
        ]
      },
      {
        "id": "switch-builtin",
        "title": "Servidores MCP integrados de Switch",
        "lede": "El escritorio de Switch ofrece servidores MCP de uso común con instalación en un clic, distribuidos dinámicamente entre CLI según visible_to.",
        "items": [
          {
            "name": "GitHub",
            "desc": "Leer y escribir issues / PR / archivos.",
            "tag": "Integrado"
          },
          {
            "name": "PostgreSQL",
            "desc": "Consultar la base de datos.",
            "tag": "Integrado"
          },
          {
            "name": "Filesystem",
            "desc": "Leer y escribir archivos locales.",
            "tag": "Integrado"
          },
          {
            "name": "Slack",
            "desc": "Enviar mensajes / leer canales.",
            "tag": "Integrado"
          }
        ]
      },
      {
        "id": "ai-clients",
        "title": "Clientes de IA",
        "lede": "Solo tienes que rellenar base_url y la API Key para conversar, sin escribir código. Consulta los pasos completos en cada guía de conexión de cliente.",
        "items": [
          {
            "name": "Cherry Studio",
            "desc": "Cliente de escritorio multimodelo; rellena base_url + Key y listo.",
            "tag": null
          },
          {
            "name": "Lobe Chat",
            "desc": "UI de conversación Web / escritorio de código abierto, con endpoint personalizado compatible con OpenAI.",
            "tag": null
          },
          {
            "name": "OpenCat",
            "desc": "Cliente nativo de iOS / macOS, con conexión mediante dominio de API personalizado.",
            "tag": null
          },
          {
            "name": "Otros clientes",
            "desc": "Configuración genérica para cualquier cliente compatible con OpenAI, como NextChat / ChatBox.",
            "tag": null
          }
        ]
      },
      {
        "id": "sdk-protocol",
        "title": "SDK y protocolos del ecosistema",
        "lede": "Compatible con los SDK y protocolos estándar; basta cambiar una línea de base_url en el código existente para migrar.",
        "items": [
          {
            "name": "OpenAI SDK",
            "desc": "Totalmente compatible con Python / Node.js / Go; solo cambia base_url y api_key.",
            "tag": "SDK"
          },
          {
            "name": "LangGraph",
            "desc": "LumenCheckpointer reemplaza directamente a SqliteSaver, conectando con la persistencia de Kova.",
            "tag": null
          },
          {
            "name": "OpenTelemetry",
            "desc": "Lumen exporta Trace mediante OTLP a Grafana Tempo / Datadog APM.",
            "tag": null
          },
          {
            "name": "OIDC / OAuth2",
            "desc": "Federación de identidad unificada con el IdP corporativo, mediante integración estándar OIDC / OAuth2.",
            "tag": null
          }
        ]
      }
    ]
  },
  "fr": {
    "frontmatter": {
      "title": "Catalogue d'intégrations et MCP",
      "description": "Aperçu des serveurs MCP, des outils intégrés Switch, des clients IA et de la compatibilité SDK/protocole de tous les produits Lurus ; parcourez par catégorie pour vous connecter."
    },
    "ui": {
      "eyebrow": "Catalogue d'intégrations",
      "title": "Catalogue d'intégrations et MCP",
      "lede": "Parcourez par catégorie : MCP des produits Lurus, serveurs intégrés Switch, clients IA, SDK et compatibilité protocole. Chaque carte mène directement à la documentation d'intégration.",
      "calloutTitle": "Cette page est pilotée par les données",
      "calloutBody": "Le catalogue provient d'un fichier de données maintenu : modifiez-le, reconstruisez et tout se synchronise ; chaque entrée correspond à une capacité réellement livrée.",
      "catEyebrow": "Catégories d'intégration",
      "nextTitle": "Étape suivante",
      "next": [
        "Switch — gestion unifiée du MCP",
        "Structures de données / Schema",
        "Démarrage rapide",
        "Intégration client"
      ]
    },
    "categories": [
      {
        "id": "product-mcp",
        "title": "MCP des produits Lurus",
        "lede": "Les produits Lurus exposent leurs capacités sous forme de serveurs MCP en tant qu'outils d'agent, appelables par des clients MCP comme Claude / Codex.",
        "items": [
          {
            "name": "Kova",
            "desc": "Le moteur d'exécution d'agents est exposé comme outil MCP (kova mcp serve), permettant à Claude/Codex de piloter directement des agents persistants.",
            "tag": "MCP"
          },
          {
            "name": "MemX",
            "desc": "Lecture/écriture de la mémoire en tant qu'outils d'agent : memory_add / memory_search / memory_delete, avec des paramètres alignés sur l'API REST.",
            "tag": "MCP"
          },
          {
            "name": "Lumen",
            "desc": "Trace / Replay exposés aux agents : le débogage et la relecture sans coût sont appelables par les clients MCP.",
            "tag": "MCP"
          }
        ]
      },
      {
        "id": "switch-builtin",
        "title": "Serveurs MCP intégrés à Switch",
        "lede": "Le bureau Switch fournit des serveurs MCP courants installables en un clic, distribués dynamiquement entre CLI selon visible_to.",
        "items": [
          {
            "name": "GitHub",
            "desc": "Lecture/écriture des issues / PR / fichiers.",
            "tag": "Intégré"
          },
          {
            "name": "PostgreSQL",
            "desc": "Interroger la base de données.",
            "tag": "Intégré"
          },
          {
            "name": "Filesystem",
            "desc": "Lecture/écriture des fichiers locaux.",
            "tag": "Intégré"
          },
          {
            "name": "Slack",
            "desc": "Envoyer des messages / lire les canaux.",
            "tag": "Intégré"
          }
        ]
      },
      {
        "id": "ai-clients",
        "title": "Clients IA",
        "lede": "Renseignez base_url et la clé API pour dialoguer, sans écrire de code. Procédure complète dans le guide d'intégration de chaque client.",
        "items": [
          {
            "name": "Cherry Studio",
            "desc": "Client de bureau multi-modèles : renseignez base_url + clé et c'est prêt.",
            "tag": null
          },
          {
            "name": "Lobe Chat",
            "desc": "Interface de conversation Web / bureau open source, avec point de terminaison compatible OpenAI personnalisable.",
            "tag": null
          },
          {
            "name": "OpenCat",
            "desc": "Client natif iOS / macOS, intégration via domaine API personnalisé.",
            "tag": null
          },
          {
            "name": "Autres clients",
            "desc": "Configuration générique pour tout client compatible OpenAI comme NextChat / ChatBox.",
            "tag": null
          }
        ]
      },
      {
        "id": "sdk-protocol",
        "title": "SDK et protocoles de l'écosystème",
        "lede": "Compatible avec les SDK et protocoles standards : migrez votre code existant en changeant une seule ligne de base_url.",
        "items": [
          {
            "name": "OpenAI SDK",
            "desc": "Pleinement compatible Python / Node.js / Go : changez seulement base_url et api_key.",
            "tag": "SDK"
          },
          {
            "name": "LangGraph",
            "desc": "LumenCheckpointer remplace directement SqliteSaver et se branche sur la persistance Kova.",
            "tag": null
          },
          {
            "name": "OpenTelemetry",
            "desc": "Lumen exporte les traces en OTLP vers Grafana Tempo / Datadog APM.",
            "tag": null
          },
          {
            "name": "OIDC / OAuth2",
            "desc": "Fédération d'identité unifiée avec l'IdP de l'entreprise, intégration OIDC / OAuth2 standard.",
            "tag": null
          }
        ]
      }
    ]
  }
}

export const modelsTableTr: Record<Locale, ModelsTableTr> = {
  "en": {
    "headers": {
      "model": "Model",
      "context": "Context Length",
      "price": "Pricing",
      "status": "Status",
      "tags": "Tags"
    },
    "status": {
      "available": "Available",
      "beta": "Beta",
      "deprecated": "Deprecated"
    },
    "vendorNames": {
      "DeepSeek": "DeepSeek",
      "Google Gemini": "Google Gemini",
      "OpenAI": "OpenAI",
      "Anthropic Claude": "Anthropic Claude",
      "图像生成": "Image Generation"
    },
    "taglines": {
      "DeepSeek": "Everyday chat, code generation, Chinese writing, math reasoning",
      "Google Gemini": "Long-document analysis, image understanding, multi-turn dialogue",
      "OpenAI": "Complex tasks, specialized domains, English-first",
      "Anthropic Claude": "Long-text processing, creative writing, safety-sensitive scenarios",
      "图像生成": "Artistic-style creation, precise instruction following"
    },
    "tags": {
      "对话": "Chat",
      "中文": "Chinese",
      "推理": "Reasoning",
      "数学": "Math",
      "代码": "Code",
      "最新": "Latest",
      "多模态": "Multimodal",
      "长上下文": "Long Context",
      "快速": "Fast",
      "图像": "Image",
      "强推理": "Strong Reasoning",
      "高性价比": "Cost-Effective",
      "稳定": "Stable",
      "经典": "Classic",
      "均衡": "Balanced",
      "最强推理": "Top Reasoning",
      "艺术": "Artistic"
    }
  },
  "ja": {
    "headers": {
      "model": "モデル名",
      "context": "コンテキスト長",
      "price": "料金",
      "status": "ステータス",
      "tags": "タグ"
    },
    "status": {
      "available": "利用可能",
      "beta": "Beta",
      "deprecated": "提供終了"
    },
    "vendorNames": {
      "DeepSeek": "DeepSeek",
      "Google Gemini": "Google Gemini",
      "OpenAI": "OpenAI",
      "Anthropic Claude": "Anthropic Claude",
      "图像生成": "画像生成"
    },
    "taglines": {
      "DeepSeek": "日常会話、コード生成、中国語ライティング、数学推論",
      "Google Gemini": "長文ドキュメント分析、画像・テキスト理解、マルチターン対話",
      "OpenAI": "複雑なタスク、専門領域、英語優先",
      "Anthropic Claude": "長文処理、クリエイティブライティング、セキュリティ重視のシーン",
      "图像生成": "アート風の制作、精密な指示への追従"
    },
    "tags": {
      "对话": "対話",
      "中文": "中国語",
      "推理": "推論",
      "数学": "数学",
      "代码": "コード",
      "最新": "最新",
      "多模态": "マルチモーダル",
      "长上下文": "長コンテキスト",
      "快速": "高速",
      "图像": "画像",
      "强推理": "強力な推論",
      "高性价比": "高コスパ",
      "稳定": "安定",
      "经典": "定番",
      "均衡": "バランス型",
      "最强推理": "最強の推論",
      "艺术": "アート"
    }
  },
  "ko": {
    "headers": {
      "model": "모델명",
      "context": "컨텍스트 길이",
      "price": "가격",
      "status": "상태",
      "tags": "태그"
    },
    "status": {
      "available": "사용 가능",
      "beta": "Beta",
      "deprecated": "지원 종료"
    },
    "vendorNames": {
      "DeepSeek": "DeepSeek",
      "Google Gemini": "Google Gemini",
      "OpenAI": "OpenAI",
      "Anthropic Claude": "Anthropic Claude",
      "图像生成": "이미지 생성"
    },
    "taglines": {
      "DeepSeek": "일상 대화, 코드 생성, 중국어 작문, 수학 추론",
      "Google Gemini": "장문 문서 분석, 이미지·텍스트 이해, 멀티턴 대화",
      "OpenAI": "복잡한 작업, 전문 분야, 영어 우선",
      "Anthropic Claude": "장문 텍스트 처리, 창작 글쓰기, 보안 민감 시나리오",
      "图像生成": "예술 스타일 창작, 정밀한 지시 준수"
    },
    "tags": {
      "对话": "대화",
      "中文": "중국어",
      "推理": "추론",
      "数学": "수학",
      "代码": "코드",
      "最新": "최신",
      "多模态": "멀티모달",
      "长上下文": "긴 컨텍스트",
      "快速": "빠름",
      "图像": "이미지",
      "强推理": "강력한 추론",
      "高性价比": "가성비",
      "稳定": "안정",
      "经典": "클래식",
      "均衡": "균형",
      "最强推理": "최강 추론",
      "艺术": "예술"
    }
  },
  "es": {
    "headers": {
      "model": "Nombre del modelo",
      "context": "Longitud de contexto",
      "price": "Precio",
      "status": "Estado",
      "tags": "Etiquetas"
    },
    "status": {
      "available": "Disponible",
      "beta": "Beta",
      "deprecated": "Retirado"
    },
    "vendorNames": {
      "DeepSeek": "DeepSeek",
      "Google Gemini": "Google Gemini",
      "OpenAI": "OpenAI",
      "Anthropic Claude": "Anthropic Claude",
      "图像生成": "Generación de imágenes"
    },
    "taglines": {
      "DeepSeek": "Conversación cotidiana, generación de código, escritura en chino y razonamiento matemático",
      "Google Gemini": "Análisis de documentos largos, comprensión de texto e imagen y conversación multironda",
      "OpenAI": "Tareas complejas, dominios especializados y prioridad en inglés",
      "Anthropic Claude": "Procesamiento de textos largos, escritura creativa y escenarios sensibles a la seguridad",
      "图像生成": "Creación de estilos artísticos y seguimiento preciso de instrucciones"
    },
    "tags": {
      "对话": "Conversación",
      "中文": "Chino",
      "推理": "Razonamiento",
      "数学": "Matemáticas",
      "代码": "Código",
      "最新": "Más reciente",
      "多模态": "Multimodal",
      "长上下文": "Contexto largo",
      "快速": "Rápido",
      "图像": "Imagen",
      "强推理": "Razonamiento avanzado",
      "高性价比": "Buena relación calidad-precio",
      "稳定": "Estable",
      "经典": "Clásico",
      "均衡": "Equilibrado",
      "最强推理": "Máximo razonamiento",
      "艺术": "Artístico"
    }
  },
  "fr": {
    "headers": {
      "model": "Nom du modèle",
      "context": "Longueur de contexte",
      "price": "Tarification",
      "status": "État",
      "tags": "Étiquettes"
    },
    "status": {
      "available": "Disponible",
      "beta": "Beta",
      "deprecated": "Retiré"
    },
    "vendorNames": {
      "DeepSeek": "DeepSeek",
      "Google Gemini": "Google Gemini",
      "OpenAI": "OpenAI",
      "Anthropic Claude": "Anthropic Claude",
      "图像生成": "Génération d'images"
    },
    "taglines": {
      "DeepSeek": "Conversation courante, génération de code, rédaction en chinois, raisonnement mathématique",
      "Google Gemini": "Analyse de longs documents, compréhension texte-image, conversation multi-tours",
      "OpenAI": "Tâches complexes, domaines spécialisés, priorité à l'anglais",
      "Anthropic Claude": "Traitement de longs textes, écriture créative, contextes sensibles à la sécurité",
      "图像生成": "Création de styles artistiques, suivi précis des instructions"
    },
    "tags": {
      "对话": "Conversation",
      "中文": "Chinois",
      "推理": "Raisonnement",
      "数学": "Mathématiques",
      "代码": "Code",
      "最新": "Dernier",
      "多模态": "Multimodal",
      "长上下文": "Contexte long",
      "快速": "Rapide",
      "图像": "Image",
      "强推理": "Raisonnement avancé",
      "高性价比": "Bon rapport qualité-prix",
      "稳定": "Stable",
      "经典": "Classique",
      "均衡": "Équilibré",
      "最强推理": "Raisonnement maximal",
      "艺术": "Artistique"
    }
  }
}
