// AUTO-GENERATED by tmp-i18n/assemble.ts — do not edit by hand.
// Source of truth for the zh strings: docs/.vitepress/data/{products,glossary}.ts.
// Regenerate: re-run the data-layer i18n extract → translate → assemble pipeline.

export type Locale = 'en' | 'ja' | 'ko' | 'es' | 'fr'

export interface ProductTr {
  name: string
  fullName: string
  tagline: string
  nextSteps: string[]
}

export interface UiTr {
  hero: {
    title: string
    taglineLead: string
    taglineAccent: string
    taglineTail: string
    btnStart: string
    btnKey: string
    btnConsole: string
    metrics: string[]
  }
  related: { heading: string; paired: string; referenced: string }
  term: { more: string }
}

export const productTr: Record<Locale, Record<string, ProductTr>> = {
  "en": {
    "lurus-api": {
      "name": "Lurus API",
      "fullName": "Lurus API — Unified LLM Gateway",
      "tagline": "One API Key for 50+ AI models, fully compatible with the OpenAI SDK",
      "nextSteps": [
        "Quickstart",
        "Supported Models",
        "Console"
      ]
    },
    "kova": {
      "name": "Kova",
      "fullName": "Kova — Durable Execution Engine for AI Agents",
      "tagline": "A WAL-First agent engine built in Rust — auto-recovers from crashes, 3μs scheduling",
      "nextSteps": [
        "Quickstart",
        "Core Concepts",
        "API Reference"
      ]
    },
    "memx": {
      "name": "MemX",
      "fullName": "MemX — Adaptive Memory Engine for AI",
      "tagline": "Zero-LLM-cost AI memory engine · bio-inspired forgetting curve · 12 PII filters",
      "nextSteps": [
        "Quickstart",
        "Core Concepts",
        "Architecture"
      ]
    },
    "lucrum": {
      "name": "Lucrum",
      "fullName": "Lucrum — AI Quantitative Trading Platform",
      "tagline": "Describe strategies in natural language — AI generates vnpy code and backtests · 11 investment advisors",
      "nextSteps": [
        "Quickstart",
        "Strategy Marketplace",
        "Trading Platform"
      ]
    },
    "switch": {
      "name": "Switch",
      "fullName": "Switch — AI Tooling Control Center",
      "tagline": "Manage config, MCP, and cost for 5 AI coding CLIs from one desktop app",
      "nextSteps": [
        "Installation",
        "Configuration",
        "User Guide"
      ]
    },
    "creator": {
      "name": "Creator",
      "fullName": "Creator — AI Content Factory",
      "tagline": "Paste a video link — AI rewrites for three platforms and auto-publishes",
      "nextSteps": [
        "Installation",
        "User Guide",
        "Use Cases"
      ]
    },
    "lumen": {
      "name": "Lumen",
      "fullName": "Lumen — Observability and Reliability for Agents",
      "tagline": "Replay · Crash Recovery · Cost Tracking — three tools in one for agents",
      "nextSteps": [
        "Quickstart",
        "Python SDK",
        "CLI Reference"
      ]
    },
    "forge": {
      "name": "Forge",
      "fullName": "Forge — AI Product Development Workbench",
      "tagline": "\"Everything is a conversation\" · dual-core Ontology + Session (internal R&D)",
      "nextSteps": [
        "Product Philosophy",
        "Ontology",
        "Session Workflow"
      ]
    },
    "platform": {
      "name": "Accounts & Billing",
      "fullName": "Lurus Platform — Accounts & Billing",
      "tagline": "Unified accounts · subscription plans · Lubei wallet · VIP tiers",
      "nextSteps": [
        "Platform Overview",
        "Billing Details",
        "FAQ"
      ]
    },
    "auth": {
      "name": "Unified Identity",
      "fullName": "Lurus Auth — Unified Identity",
      "tagline": "Cross-product SSO · Passkey · MFA · OIDC/OAuth2 · enterprise SSO federation",
      "nextSteps": [
        "Overview & Endpoints",
        "OIDC / OAuth2",
        "API Authentication",
        "Auth Console"
      ]
    },
    "api-ref": {
      "name": "API Reference",
      "fullName": "API Reference — OpenAI-Compatible Endpoints",
      "tagline": "Complete endpoint docs · error codes · request examples",
      "nextSteps": [
        "API Overview",
        "Authentication",
        "Chat Completions"
      ]
    },
    "arch": {
      "name": "System Architecture",
      "fullName": "System Architecture — Hybrid Cloud · GitOps · Observability",
      "tagline": "Infrastructure shared across 12 products, explained in one diagram",
      "nextSteps": [
        "View Architecture"
      ]
    }
  },
  "ja": {
    "lurus-api": {
      "name": "Lurus API",
      "fullName": "Lurus API — LLM 統合ゲートウェイ",
      "tagline": "1 つの API Key で 50+ の AI モデルに接続、OpenAI SDK と完全互換",
      "nextSteps": [
        "クイックスタート",
        "対応モデル",
        "コンソール"
      ]
    },
    "kova": {
      "name": "Kova",
      "fullName": "Kova — AI Agent 永続実行エンジン",
      "tagline": "Rust で構築した WAL-First Agent エンジン、クラッシュ時に自動復旧、3μs スケジューリング",
      "nextSteps": [
        "クイックスタート",
        "コアコンセプト",
        "API リファレンス"
      ]
    },
    "memx": {
      "name": "MemX",
      "fullName": "MemX — AI 適応型メモリエンジン",
      "tagline": "LLM コストゼロの AI メモリエンジン · 生体模倣の忘却曲線 · 12 種類の PII フィルタ",
      "nextSteps": [
        "クイックスタート",
        "コアコンセプト",
        "アーキテクチャ設計"
      ]
    },
    "lucrum": {
      "name": "Lucrum",
      "fullName": "Lucrum — AI クオンツ取引プラットフォーム",
      "tagline": "自然言語で戦略を記述し、AI が vnpy コードを生成してバックテスト · 11 名の投資アドバイザー",
      "nextSteps": [
        "クイックスタート",
        "戦略マーケット",
        "取引プラットフォーム"
      ]
    },
    "switch": {
      "name": "Switch",
      "fullName": "Switch — AI ツール管理センター",
      "tagline": "デスクトップで 5 つの AI コーディング CLI の設定 · MCP · コストを一元管理",
      "nextSteps": [
        "インストールガイド",
        "設定方法",
        "ユーザーマニュアル"
      ]
    },
    "creator": {
      "name": "Creator",
      "fullName": "Creator — AI コンテンツファクトリー",
      "tagline": "動画リンクを貼り付けるだけ、AI が 3 プラットフォーム向けにリライト + 自動投稿",
      "nextSteps": [
        "インストールガイド",
        "ユーザーマニュアル",
        "活用事例"
      ]
    },
    "lumen": {
      "name": "Lumen",
      "fullName": "Lumen — Agent 可観測性・信頼性ツール",
      "tagline": "Replay · Crash Recovery · Cost Tracking — Agent 向け 3-in-1",
      "nextSteps": [
        "クイックスタート",
        "Python SDK",
        "CLI マニュアル"
      ]
    },
    "forge": {
      "name": "Forge",
      "fullName": "Forge — AI プロダクト開発ワークベンチ",
      "tagline": "「すべては対話」 · Ontology + Session のデュアルコア（社内 R&D）",
      "nextSteps": [
        "プロダクト哲学",
        "Ontology",
        "Session ワークフロー"
      ]
    },
    "platform": {
      "name": "アカウントと課金",
      "fullName": "Lurus Platform — アカウントと課金",
      "tagline": "統合アカウント · サブスクリプションプラン · Lubei ウォレット · VIP 体系",
      "nextSteps": [
        "プラットフォーム概要",
        "課金の詳細",
        "よくある質問"
      ]
    },
    "auth": {
      "name": "統合 ID 認証",
      "fullName": "Lurus Auth — 統合 ID 認証",
      "tagline": "全プロダクト SSO · Passkey · MFA · OIDC/OAuth2 · エンタープライズ SSO フェデレーション",
      "nextSteps": [
        "概要と接続ポイント",
        "OIDC / OAuth2",
        "API 認証",
        "認証コンソール"
      ]
    },
    "api-ref": {
      "name": "API リファレンス",
      "fullName": "API リファレンス — OpenAI 互換エンドポイントマニュアル",
      "tagline": "完全なエンドポイントドキュメント · エラーコード · リクエスト例",
      "nextSteps": [
        "API 概要",
        "認証",
        "Chat Completions"
      ]
    },
    "arch": {
      "name": "システムアーキテクチャ",
      "fullName": "システムアーキテクチャ — ハイブリッドクラウド · GitOps · 可観測性",
      "tagline": "12 のプロダクトが共有する基盤を 1 枚の図で明快に",
      "nextSteps": [
        "アーキテクチャを見る"
      ]
    }
  },
  "ko": {
    "lurus-api": {
      "name": "Lurus API",
      "fullName": "Lurus API — LLM 통합 게이트웨이",
      "tagline": "하나의 API Key로 50+ AI 모델 연동, OpenAI SDK와 완전 호환",
      "nextSteps": [
        "빠른 시작",
        "지원 모델",
        "콘솔"
      ]
    },
    "kova": {
      "name": "Kova",
      "fullName": "Kova — AI Agent 지속 실행 엔진",
      "tagline": "Rust로 구축한 WAL-First Agent 엔진, 크래시 시 자동 복구, 3μs 스케줄링",
      "nextSteps": [
        "빠른 시작",
        "핵심 개념",
        "API 레퍼런스"
      ]
    },
    "memx": {
      "name": "MemX",
      "fullName": "MemX — AI 적응형 메모리 엔진",
      "tagline": "LLM 비용 제로의 AI 메모리 엔진 · 생체모방 망각 곡선 · 12종 PII 필터링",
      "nextSteps": [
        "빠른 시작",
        "핵심 개념",
        "아키텍처 설계"
      ]
    },
    "lucrum": {
      "name": "Lucrum",
      "fullName": "Lucrum — AI 퀀트 트레이딩 플랫폼",
      "tagline": "자연어로 전략을 기술하면 AI가 vnpy 코드를 생성하고 백테스트 · 11명의 투자 어드바이저",
      "nextSteps": [
        "빠른 시작",
        "전략 마켓",
        "트레이딩 플랫폼"
      ]
    },
    "switch": {
      "name": "Switch",
      "fullName": "Switch — AI 도구 관리 센터",
      "tagline": "데스크톱에서 5종 AI 코딩 CLI의 설정 · MCP · 비용을 통합 관리",
      "nextSteps": [
        "설치 가이드",
        "설정 설명",
        "사용 매뉴얼"
      ]
    },
    "creator": {
      "name": "Creator",
      "fullName": "Creator — AI 콘텐츠 팩토리",
      "tagline": "영상 링크를 붙여넣으면 AI가 3개 플랫폼용으로 리라이팅 + 자동 게시",
      "nextSteps": [
        "설치 가이드",
        "사용 매뉴얼",
        "활용 사례"
      ]
    },
    "lumen": {
      "name": "Lumen",
      "fullName": "Lumen — Agent 가관측성 및 신뢰성 도구",
      "tagline": "Replay · Crash Recovery · Cost Tracking — Agent 올인원",
      "nextSteps": [
        "빠른 시작",
        "Python SDK",
        "CLI 매뉴얼"
      ]
    },
    "forge": {
      "name": "Forge",
      "fullName": "Forge — AI 제품 개발 워크벤치",
      "tagline": "\"모든 것은 대화\" · Ontology + Session 듀얼 코어 (내부 R&D)",
      "nextSteps": [
        "제품 철학",
        "Ontology",
        "Session 워크플로우"
      ]
    },
    "platform": {
      "name": "계정 및 과금",
      "fullName": "Lurus Platform — 계정 및 과금",
      "tagline": "통합 계정 · 구독 플랜 · Lubei 지갑 · VIP 체계",
      "nextSteps": [
        "플랫폼 개요",
        "과금 상세",
        "자주 묻는 질문"
      ]
    },
    "auth": {
      "name": "통합 ID 인증",
      "fullName": "Lurus Auth — 통합 ID 인증",
      "tagline": "전 제품 SSO · Passkey · MFA · OIDC/OAuth2 · 엔터프라이즈 SSO 페더레이션",
      "nextSteps": [
        "개요 및 연동 지점",
        "OIDC / OAuth2",
        "API 인증",
        "인증 콘솔"
      ]
    },
    "api-ref": {
      "name": "API 레퍼런스",
      "fullName": "API 레퍼런스 — OpenAI 호환 엔드포인트 매뉴얼",
      "tagline": "전체 엔드포인트 문서 · 오류 코드 · 요청 예시",
      "nextSteps": [
        "API 개요",
        "인증",
        "Chat Completions"
      ]
    },
    "arch": {
      "name": "시스템 아키텍처",
      "fullName": "시스템 아키텍처 — 하이브리드 클라우드 · GitOps · 가관측성",
      "tagline": "12개 제품이 공유하는 인프라를 한 장의 그림으로 설명",
      "nextSteps": [
        "아키텍처 보기"
      ]
    }
  },
  "es": {
    "lurus-api": {
      "name": "Lurus API",
      "fullName": "Lurus API — gateway unificado de LLM",
      "tagline": "Una sola API Key para acceder a más de 50 modelos de IA, totalmente compatible con el SDK de OpenAI",
      "nextSteps": [
        "Inicio rápido",
        "Modelos compatibles",
        "Consola"
      ]
    },
    "kova": {
      "name": "Kova",
      "fullName": "Kova — motor de ejecución persistente para agentes de IA",
      "tagline": "Motor de agentes WAL-First construido en Rust, con recuperación automática ante fallos y planificación de 3μs",
      "nextSteps": [
        "Inicio rápido",
        "Conceptos básicos",
        "Referencia de la API"
      ]
    },
    "memx": {
      "name": "MemX",
      "fullName": "MemX — motor de memoria adaptativa para IA",
      "tagline": "Motor de memoria para IA con cero coste de LLM · curva de olvido biomimética · 12 filtros de PII",
      "nextSteps": [
        "Inicio rápido",
        "Conceptos básicos",
        "Diseño de la arquitectura"
      ]
    },
    "lucrum": {
      "name": "Lucrum",
      "fullName": "Lucrum — plataforma de trading cuantitativo con IA",
      "tagline": "Describe la estrategia en lenguaje natural, la IA genera el código vnpy y ejecuta el backtest · 11 asesores de inversión",
      "nextSteps": [
        "Inicio rápido",
        "Mercado de estrategias",
        "Plataforma de trading"
      ]
    },
    "switch": {
      "name": "Switch",
      "fullName": "Switch — centro de gestión de herramientas de IA",
      "tagline": "Gestión unificada en el escritorio de la configuración de 5 CLI de programación con IA · MCP · costes",
      "nextSteps": [
        "Guía de instalación",
        "Configuración",
        "Manual de uso"
      ]
    },
    "creator": {
      "name": "Creator",
      "fullName": "Creator — fábrica de contenido con IA",
      "tagline": "Pega el enlace de un vídeo y la IA lo reescribe para tres plataformas y lo publica automáticamente",
      "nextSteps": [
        "Guía de instalación",
        "Manual de uso",
        "Casos de uso"
      ]
    },
    "lumen": {
      "name": "Lumen",
      "fullName": "Lumen — herramienta de observabilidad y fiabilidad para agentes",
      "tagline": "Replay · Crash Recovery · Cost Tracking — tres en uno para agentes",
      "nextSteps": [
        "Inicio rápido",
        "Python SDK",
        "Manual de la CLI"
      ]
    },
    "forge": {
      "name": "Forge",
      "fullName": "Forge — banco de trabajo para el desarrollo de productos con IA",
      "tagline": "\"Todo es conversación\" · doble núcleo Ontology + Session (I+D interno)",
      "nextSteps": [
        "Filosofía del producto",
        "Ontology",
        "Flujo de trabajo de Session"
      ]
    },
    "platform": {
      "name": "Cuenta y facturación",
      "fullName": "Lurus Platform — cuenta y facturación",
      "tagline": "Cuenta unificada · planes de suscripción · monedero Lubei · sistema VIP",
      "nextSteps": [
        "Descripción de la plataforma",
        "Detalles de la facturación",
        "Preguntas frecuentes"
      ]
    },
    "auth": {
      "name": "Identidad unificada",
      "fullName": "Lurus Auth — identidad unificada",
      "tagline": "SSO para todos los productos · Passkey · MFA · OIDC/OAuth2 · federación de SSO empresarial",
      "nextSteps": [
        "Descripción y puntos de acceso",
        "OIDC / OAuth2",
        "Autenticación de la API",
        "Consola de autenticación"
      ]
    },
    "api-ref": {
      "name": "Referencia de la API",
      "fullName": "Referencia de la API — manual de endpoints compatibles con OpenAI",
      "tagline": "Documentación completa de endpoints · códigos de error · ejemplos de solicitud",
      "nextSteps": [
        "Descripción de la API",
        "Autenticación",
        "Chat Completions"
      ]
    },
    "arch": {
      "name": "Arquitectura del sistema",
      "fullName": "Arquitectura del sistema — nube híbrida · GitOps · observabilidad",
      "tagline": "La infraestructura compartida por los 12 productos, explicada en un solo diagrama",
      "nextSteps": [
        "Ver la arquitectura"
      ]
    }
  },
  "fr": {
    "lurus-api": {
      "name": "Lurus API",
      "fullName": "Lurus API — passerelle LLM unifiée",
      "tagline": "Une seule API Key pour accéder à 50+ modèles d'IA, entièrement compatible avec le SDK OpenAI",
      "nextSteps": [
        "Démarrage rapide",
        "Modèles pris en charge",
        "Console"
      ]
    },
    "kova": {
      "name": "Kova",
      "fullName": "Kova — moteur d'exécution persistante pour agents IA",
      "tagline": "Moteur d'agents WAL-First écrit en Rust, reprise automatique après crash, ordonnancement en 3μs",
      "nextSteps": [
        "Démarrage rapide",
        "Concepts clés",
        "Référence API"
      ]
    },
    "memx": {
      "name": "MemX",
      "fullName": "MemX — moteur de mémoire adaptative pour l'IA",
      "tagline": "Moteur de mémoire IA sans coût LLM · courbe d'oubli biomimétique · 12 filtres PII",
      "nextSteps": [
        "Démarrage rapide",
        "Concepts clés",
        "Conception de l'architecture"
      ]
    },
    "lucrum": {
      "name": "Lucrum",
      "fullName": "Lucrum — plateforme de trading quantitatif IA",
      "tagline": "Décrivez votre stratégie en langage naturel, l'IA génère le code vnpy et le backteste · 11 conseillers en investissement",
      "nextSteps": [
        "Démarrage rapide",
        "Marché des stratégies",
        "Plateforme de trading"
      ]
    },
    "switch": {
      "name": "Switch",
      "fullName": "Switch — centre de gestion des outils IA",
      "tagline": "Gérez de façon unifiée la configuration de 5 CLI de programmation IA · MCP · coûts, depuis le bureau",
      "nextSteps": [
        "Guide d'installation",
        "Configuration",
        "Manuel d'utilisation"
      ]
    },
    "creator": {
      "name": "Creator",
      "fullName": "Creator — usine à contenu IA",
      "tagline": "Collez un lien vidéo, l'IA le réécrit pour trois plateformes et le publie automatiquement",
      "nextSteps": [
        "Guide d'installation",
        "Manuel d'utilisation",
        "Cas d'usage"
      ]
    },
    "lumen": {
      "name": "Lumen",
      "fullName": "Lumen — outil d'observabilité et de fiabilité pour agents",
      "tagline": "Replay · Crash Recovery · Cost Tracking — trois fonctions en une pour vos agents",
      "nextSteps": [
        "Démarrage rapide",
        "SDK Python",
        "Manuel CLI"
      ]
    },
    "forge": {
      "name": "Forge",
      "fullName": "Forge — atelier de développement de produits IA",
      "tagline": "\"Tout est conversation\" · Ontology + Session, deux cœurs (R&D interne)",
      "nextSteps": [
        "Philosophie du produit",
        "Ontology",
        "Flux de travail Session"
      ]
    },
    "platform": {
      "name": "Comptes et facturation",
      "fullName": "Lurus Platform — comptes et facturation",
      "tagline": "Compte unifié · forfaits d'abonnement · portefeuille Lubei · système VIP",
      "nextSteps": [
        "Présentation de la plateforme",
        "Facturation en détail",
        "Questions fréquentes"
      ]
    },
    "auth": {
      "name": "Authentification d'identité unifiée",
      "fullName": "Lurus Auth — authentification d'identité unifiée",
      "tagline": "SSO sur tous les produits · Passkey · MFA · OIDC/OAuth2 · fédération SSO d'entreprise",
      "nextSteps": [
        "Présentation et points d'accès",
        "OIDC / OAuth2",
        "Authentification API",
        "Console d'authentification"
      ]
    },
    "api-ref": {
      "name": "Référence API",
      "fullName": "Référence API — manuel des endpoints compatibles OpenAI",
      "tagline": "Documentation complète des endpoints · codes d'erreur · exemples de requêtes",
      "nextSteps": [
        "Présentation de l'API",
        "Authentification",
        "Chat Completions"
      ]
    },
    "arch": {
      "name": "Architecture système",
      "fullName": "Architecture système — cloud hybride · GitOps · observabilité",
      "tagline": "L'infrastructure partagée des 12 produits, expliquée d'un seul schéma",
      "nextSteps": [
        "Voir l'architecture"
      ]
    }
  }
}

export const glossaryDefs: Record<Locale, Record<string, string>> = {
  "en": {
    "API Key": "A secret credential for accessing the API, much like a password. Each Key can have its own quota and permissions.",
    "Bearer Token": "An HTTP authentication scheme that carries the credential in the request header as \"Bearer sk-xxx\".",
    "Rate Limit": "A cap on the number of requests allowed per unit of time, used to prevent abuse and overload.",
    "Streaming": "A streaming response where the AI model returns results token by token rather than waiting for full generation, reducing time to first token.",
    "Token": "The smallest unit an LLM uses to process text. Roughly 1.5 characters per token for Chinese and 4 characters per token for English.",
    "Webhook": "A server-initiated push of event notifications to a URL you specify, such as payment success or subscription expiry.",
    "SDK": "A software development kit providing ready-made functions and classes to simplify API calls. Lurus is compatible with the OpenAI SDK.",
    "Endpoint": "An API endpoint — a callable URL path such as /v1/chat/completions.",
    "Base URL": "The root address of the API. The Lurus Base URL is https://api.lurus.cn/v1.",
    "GitOps": "Using a Git repository as the source of truth for deployments, with automation tools such as ArgoCD syncing the desired state to the cluster.",
    "ArgoCD": "A GitOps continuous-delivery tool for Kubernetes that watches a Git repository for changes and syncs them to the cluster automatically.",
    "OpenTelemetry": "An open standard for observability that unifies the collection and transport of the three signals — traces, metrics, and logs.",
    "OpenAPI": "An open specification for describing REST APIs (formerly Swagger). Lurus data structures are auto-generated from the gateway's OpenAPI spec.",
    "Schema": "A definition of a data structure that specifies the name, type, and required status of each field in a request or response.",
    "OIDC": "OpenID Connect, an identity authentication standard built on OAuth 2.0. Lurus implements it with Casdoor.",
    "Passkey": "A passwordless authentication method based on the WebAuthn standard, completed via device fingerprint, Face ID, or a security key.",
    "MFA": "Multi-factor authentication, which requires two or more credentials at once (password + TOTP, password + Passkey, etc.).",
    "PAT": "Personal Access Token — a long-lived API access token generated by the user to replace passwords for automation.",
    "JWT": "JSON Web Token — a self-contained, signed token that lets the server verify identity without a database lookup.",
    "Casdoor": "The open-source identity platform used by Lurus, providing OIDC / OAuth2 / SAML / SCIM / MFA capabilities.",
    "SSO 联邦": "Enterprises connect their own IdP (Okta, Azure AD, etc.) to Lurus Auth so employees can sign in to Lurus products with their corporate accounts.",
    "WAL": "Write-Ahead Log. Every state change is written to the log before it executes, ensuring recovery from the log after a crash.",
    "Checkpoint": "A complete in-memory state snapshot written to disk. On crash recovery, the WAL is replayed starting from the most recent Checkpoint.",
    "CheckpointSaver": "The component interface in LangGraph responsible for persisting graph state; it can be swapped for implementations provided by Kova or Lumen.",
    "Agent": "An LLM-driven autonomous program: perceive input → reason → call tools → produce results.",
    "Agent Loop": "An agent's decision loop: receive input → LLM reasoning → call tools → get results → keep reasoning, until a final answer is produced.",
    "Durable Execution": "Task state is continuously written to the WAL, so the process automatically resumes from the point of interruption after a crash without re-invoking the LLM.",
    "MCP": "Model Context Protocol — an open standard that lets AI agents call external tools and data sources in a uniform way.",
    "A2A": "The Agent-to-Agent protocol, which lets multiple agents communicate directly, delegate tasks, and exchange information.",
    "Swarm": "A swarm-intelligence pattern in which a coordinator assigns tasks to multiple agents that collaborate autonomously, with no predefined fixed workflow.",
    "Ring Buffer": "A fixed-size circular storage structure. When the write pointer reaches the end it wraps around and overwrites old data; the WAL uses a power-of-2-sized ring buffer.",
    "CRC32": "A cyclic redundancy check algorithm used to detect errors in data transmission or storage. Every Kova WAL record includes a CRC32 checksum.",
    "FIFO": "First In, First Out. Kova's task scheduling uses a FIFO strategy by default.",
    "System Prompt": "A system prompt that defines the AI's role, capability boundaries, and behavioral rules. It goes first in the message array.",
    "Tool Call": "When an AI model decides during reasoning to call an external tool (such as search or a database query) and returns structured call arguments.",
    "Replay": "Reproducing an agent's execution from a persisted event sequence — debug locally without spending extra LLM tokens.",
    "ACE": "Adaptive Context Engine. The core intelligence layer of MemX, comprising four modules: knowledge distillation, deduplication, decay, and retrieval.",
    "Embedding": "A vector that converts text into a high-dimensional numeric representation, so semantically similar text lies close together in vector space. MemX generates these with a local ONNX model.",
    "Vector Search": "Finding the most semantically relevant results by computing the distance between the embeddings of the query and the stored text.",
    "Semantic Dedup": "Semantic deduplication, which uses cosine similarity to automatically identify and merge knowledge entries that mean the same thing but are worded differently.",
    "PII": "Personally identifiable information, such as API Keys, passwords, and private keys. MemX ships with 12 PII filter rules that cannot be bypassed.",
    "Reflector": "MemX's knowledge-distillation engine, which extracts high-value knowledge from conversations via rule-based pre-screening plus LLM refinement.",
    "Curator": "MemX's semantic-dedup engine, which uses cosine similarity on every write to automatically merge duplicate knowledge and detect contradictions.",
    "Decay": "Memory decay that mimics the human forgetting curve: rarely retrieved knowledge gradually loses weight, while frequently retrieved knowledge becomes more firmly established.",
    "Ebbinghaus": "The Ebbinghaus forgetting curve, the psychological law that human memory decays exponentially over time. MemX designs its memory half-life around it.",
    "Cosine Similarity": "A measure of how similar two vectors' directions are, ranging from [-1, 1]. MemX uses it to judge whether knowledge is duplicated (>=0.8 merges automatically).",
    "Knowledge Distillation": "Extracting refined, reusable knowledge entries from large volumes of conversation. MemX's Reflector engine does this automatically.",
    "Ontology": "A tree-structured description of domain knowledge (user stories, architecture, tech stack, conventions). Forge's core data model.",
    "Backtest": "Simulating strategy trades against historical market data to evaluate how a strategy would have performed in past market conditions.",
    "Sharpe Ratio": "Excess return earned per unit of risk taken. Above 1.0 is good; above 2.0 is excellent.",
    "Max Drawdown": "The maximum percentage drop from a historical peak to a subsequent trough. Below 20% is acceptable; below 10% is excellent.",
    "Stop Loss": "A preset loss threshold that automatically closes a position once reached, to limit losses. A basic risk-control measure.",
    "Adjustment": "Adjusting historical stock prices for dividends and stock splits so prices across different periods are comparable. Split into forward and backward adjustment.",
    "Round Lot": "The minimum trading unit on A-shares: 1 lot = 100 shares. Purchases must be in whole-lot multiples.",
    "Commission": "The fee a broker charges per trade. On A-shares it is typically about 0.03%, with a 5-yuan minimum.",
    "Stamp Duty": "A tax levied by the state when selling stock. The current A-share rate is 0.05% of the transaction amount.",
    "Slippage": "The difference between the expected and actual fill price. Slippage is more pronounced for large orders or illiquid instruments.",
    "Win Rate": "The share of profitable trades among all trades. Above 50% is baseline; above 60% is good.",
    "Sortino": "The Sortino ratio, similar to the Sharpe ratio but considering only downside volatility (loss risk), so it better reflects an investor's real experience.",
    "Calmar": "The Calmar ratio: annualized return divided by max drawdown. Above 1.0 means returns can cover the maximum drawdown.",
    "Decimal.js": "A JavaScript arbitrary-precision decimal library that Lucrum uses to eliminate floating-point errors in financial calculations.",
    "CtaTemplate": "vnpy's base strategy template, which defines standard lifecycle hooks such as on_bar, on_tick, and on_trade.",
    "vnpy": "An open-source Python quantitative-trading framework. Lucrum's AI-generated strategy code is built on the vnpy CtaTemplate.",
    "鹿贝": "Lurus's unified billing unit (Lubei). All product usage is charged in Lubei; 1 Lubei equals one US cent.",
    "MCP Server": "A tool service process that implements the MCP protocol, exposing callable tool capabilities (GitHub, databases, etc.) to AI agents.",
    "Provider": "A model provider such as Lurus API, OpenAI, Anthropic, or Ollama. Switch supports configuring multiple Providers and routing by rule.",
    "CLAUDE.md": "An instruction file placed at the project root that AI coding tools read to understand project context, coding conventions, and workflow.",
    "Proxy": "An OpenAI-compatible API endpoint that Switch runs locally, forwarding requests to different Providers according to routing rules.",
    "SM4-GCM": "The Chinese-national SM4 block cipher in GCM authenticated-encryption mode — the go-to symmetric encryption for SM-cryptography compliance scenarios.",
    "TCO": "Total Cost of Ownership — the full-lifecycle cost covering licensing, deployment, operations, and migration in a procurement decision.",
    "Whisper": "OpenAI's open-source speech-recognition model, used by Creator and Lumen for audio transcription.",
    "Dependency Guardian": "A planned dependency sentinel in Forge that automatically detects interface breakage across Epics and Stories.",
    "Session": "In Forge, the context container for a single product discussion, holding the complete timeline of dialogue, decisions, and agent output."
  },
  "ja": {
    "API Key": "API にアクセスするための鍵となる認証情報で、パスワードのようなものです。各 Key ごとにクォータと権限を個別に設定できます。",
    "Bearer Token": "HTTP 認証方式の一種で、リクエストヘッダーに \"Bearer sk-xxx\" の形式で認証情報を付与します。",
    "Rate Limit": "レート制限。API が単位時間あたりのリクエスト回数に設ける上限制御で、不正利用や過負荷を防ぎます。",
    "Streaming": "ストリーミング応答。AI モデルが結果を Token 単位で逐次返す（全生成を待たない）方式で、最初の文字までの遅延を低減します。",
    "Token": "LLM がテキストを処理する最小単位です。中国語は約 1.5 文字/token、英語は約 4 文字/token です。",
    "Webhook": "サーバー側から指定した URL へ、支払い成功やサブスクリプション期限切れなどのイベント通知を能動的に送信する仕組みです。",
    "SDK": "ソフトウェア開発キット。あらかじめラップされた関数やクラスを提供し、API 呼び出しを簡素化します。Lurus は OpenAI SDK と互換です。",
    "Endpoint": "API エンドポイント。/v1/chat/completions のような、呼び出し可能な URL パスです。",
    "Base URL": "API のルートアドレス。Lurus の Base URL は https://api.lurus.cn/v1 です。",
    "GitOps": "Git リポジトリをデプロイの真実の源とし、ArgoCD などの自動化ツールで期待状態をクラスタに同期する手法です。",
    "ArgoCD": "Kubernetes 向けの GitOps 継続的デリバリーツールで、Git リポジトリの変更を監視し自動でクラスタに同期します。",
    "OpenTelemetry": "可観測性領域のオープン標準で、Trace / Metric / Log の 3 つのシグナルの収集と転送を統一します。",
    "OpenAPI": "REST API を記述するオープン仕様（旧 Swagger）です。Lurus のデータ構造はゲートウェイの OpenAPI 仕様から自動同期生成されます。",
    "Schema": "データ構造の定義で、リクエスト / レスポンス中の各フィールドの名前・型・必須かどうかを規定します。",
    "OIDC": "OpenID Connect。OAuth 2.0 に基づく ID 認証標準で、Lurus は Casdoor を用いて実装しています。",
    "Passkey": "WebAuthn 標準に基づくパスワードレス認証方式で、デバイス指紋 / Face ID / セキュリティキーで認証します。",
    "MFA": "多要素認証。2 種類以上の認証情報（パスワード + TOTP、パスワード + Passkey など）を同時に求めます。",
    "PAT": "Personal Access Token。ユーザーが生成する長期の API アクセストークンで、自動化用途でパスワードの代わりに使います。",
    "JWT": "JSON Web Token。自己完結型の署名付きトークンで、サーバー側はデータベースを参照せずに ID を検証できます。",
    "Casdoor": "Lurus が採用するオープンソースの ID プラットフォームで、OIDC / OAuth2 / SAML / SCIM / MFA の機能を提供します。",
    "SSO 联邦": "企業が自社の IdP（Okta / Azure AD など）を Lurus Auth に接続し、従業員が会社アカウントで Lurus 製品にログインできる仕組みです。",
    "WAL": "Write-Ahead Log、先行書き込みログ。すべての状態変更をまずログに書いてから実行することで、クラッシュ後にログから復旧できることを保証します。",
    "Checkpoint": "チェックポイント。メモリ内の完全な状態スナップショットをディスクに書き出します。クラッシュ復旧時は直近の Checkpoint から WAL をリプレイします。",
    "CheckpointSaver": "LangGraph においてグラフ状態の永続化を担うコンポーネントインターフェースで、Kova/Lumen が提供する実装に置き換えられます。",
    "Agent": "LLM で駆動される自律的な意思決定プログラムです。入力を知覚 → 推論 → ツール呼び出し → 結果を生成します。",
    "Agent Loop": "Agent の意思決定ループ。入力受信 → LLM 推論 → ツール呼び出し → 結果取得 → 推論継続を、最終回答が生成されるまで繰り返します。",
    "Durable Execution": "永続実行。タスク状態を継続的に WAL へ書き込み、プロセスがクラッシュしても中断点から自動復旧し、LLM を重複して呼び出しません。",
    "MCP": "Model Context Protocol、モデルコンテキストプロトコル。AI Agent が外部ツールやデータソースを統一的な方法で呼び出せるようにするオープン標準です。",
    "A2A": "Agent-to-Agent プロトコル。複数の Agent が直接通信し、タスクを委譲して情報を交換できるようにします。",
    "Swarm": "群知能モード。複数の Agent がコーディネーターによってタスクを割り当てられ、固定の事前定義フローなしに自律的に協調します。",
    "Ring Buffer": "リングバッファ、固定サイズの循環ストレージ構造です。書き込みポインタが末尾に達すると先頭に巻き戻って古いデータを上書きします。WAL は power-of-2 サイズのリングバッファを使用します。",
    "CRC32": "巡回冗長検査アルゴリズムで、データ転送や保存中のエラーを検出します。Kova の各 WAL レコードには CRC32 チェックサムが含まれます。",
    "FIFO": "First In, First Out、先入れ先出しキューです。Kova のタスクスケジューリングはデフォルトで FIFO 戦略を使用します。",
    "System Prompt": "システムプロンプト。AI の役割・能力の境界・行動規範を定義し、メッセージ配列の先頭に配置します。",
    "Tool Call": "AI モデルが推論の過程で外部ツール（検索やデータベースクエリなど）の呼び出しを決定し、構造化された呼び出しパラメータを返すことです。",
    "Replay": "リプレイ。永続化済みのイベント列を使って Agent の実行過程を再現し、ローカルデバッグで追加の LLM Token を消費しません。",
    "ACE": "Adaptive Context Engine、適応型コンテキストエンジン。MemX のコアとなる知能層で、知識蒸留・重複排除・減衰・検索の 4 つのモジュールを含みます。",
    "Embedding": "埋め込みベクトル。テキストを高次元の数値ベクトルに変換し、意味的に類似するテキストがベクトル空間で近くに配置されるようにします。MemX はローカルの ONNX モデルで生成します。",
    "Vector Search": "ベクトル検索。クエリテキストと保存テキストの埋め込みベクトル距離を計算し、意味的に最も関連性の高い結果を見つけます。",
    "Semantic Dedup": "意味的重複排除。コサイン類似度により、意味は同じだが表現が異なる知識エントリを自動で識別・統合します。",
    "PII": "個人を識別できる情報で、API Key・パスワード・秘密鍵などの機密データを指します。MemX は迂回不可能な 12 種類の PII フィルタルールを内蔵しています。",
    "Reflector": "MemX の知識蒸留エンジン。ルールによる事前選別 + LLM による精緻化で、対話から高価値な知識を自動抽出します。",
    "Curator": "MemX の意味的重複排除エンジン。書き込みのたびにコサイン類似度で重複知識を自動統合し、矛盾を検出します。",
    "Decay": "メモリ減衰。人間の忘却曲線を模倣し、検索されない知識は徐々に重みを下げ、よく検索される知識ほど強固になります。",
    "Ebbinghaus": "エビングハウスの忘却曲線。人間の記憶が時間とともに指数的に減衰するという心理学の法則です。MemX はこれに基づき記憶の半減期を設計しています。",
    "Cosine Similarity": "コサイン類似度。2 つのベクトルの方向の類似度を測る指標で、値域は [-1, 1] です。MemX は知識が重複かどうかの判定に用います（>=0.8 で自動統合）。",
    "Knowledge Distillation": "知識蒸留。大量の対話から精緻で再利用可能な知識エントリを抽出します。MemX の Reflector エンジンがこの過程を自動で行います。",
    "Ontology": "オントロジー。ドメイン知識（ユーザーストーリー / アーキテクチャ / 技術スタック / 規約）をツリー構造で記述するもので、Forge のコアデータモデルです。",
    "Backtest": "バックテスト。過去の相場データを使って戦略取引をシミュレートし、過去の市場環境における戦略のパフォーマンスを評価します。",
    "Sharpe Ratio": "シャープレシオ。リスク 1 単位あたりに得られる超過リターンです。> 1.0 で優秀、> 2.0 で卓越しています。",
    "Max Drawdown": "最大ドローダウン。過去の最高値から最安値までの最大下落率です。< 20% で許容範囲、< 10% で優秀です。",
    "Stop Loss": "ストップロス（損切り）。あらかじめ設定した損失閾値で、到達すると自動的に決済して損失を抑えます。リスク管理の基本手段です。",
    "Adjustment": "権利調整。株式の過去価格に配当 / 株式分割の調整を行い、異なる時期の価格を比較可能にします。前方調整と後方調整があります。",
    "Round Lot": "単元株（手）。A 株の最小取引単位で、1 手 = 100 株です。買い注文は単元の整数倍である必要があります。",
    "Commission": "手数料。証券会社が取引ごとに徴収する費用です。A 株では一般に 0.03% 程度で、最低 5 元の下限があります。",
    "Stamp Duty": "印紙税。株式売却時に国が徴収する税金です。A 株では現在、約定金額の 0.05% が税率となっています。",
    "Slippage": "スリッページ。想定約定価格と実際の約定価格の差です。大口資金や流動性の低い銘柄ほど顕著になります。",
    "Win Rate": "勝率。利益となった取引が総取引回数に占める割合です。> 50% で標準、> 60% で良好です。",
    "Sortino": "ソルティノレシオ。シャープレシオに似ていますが下方変動（損失リスク）のみを考慮するため、投資家の実際の体感をより反映します。",
    "Calmar": "カルマーレシオ。年率リターン / 最大ドローダウンです。> 1.0 はリターンが最大ドローダウンをカバーできることを示します。",
    "Decimal.js": "JavaScript の任意精度十進数演算ライブラリで、Lucrum は金融計算における浮動小数点誤差を排除するために使用しています。",
    "CtaTemplate": "vnpy の戦略テンプレート基底クラスで、標準的な on_bar / on_tick / on_trade などのライフサイクルフックを定義します。",
    "vnpy": "Python のクオンツ取引オープンソースフレームワークで、Lurus の AI が生成する戦略コードは vnpy CtaTemplate に基づきます。",
    "鹿贝": "Lurus プラットフォームの統合課金単位（Lubei）です。すべての製品の消費は Lubei で課金され、1 Lubei = 1 米セント相当です。",
    "MCP Server": "MCP プロトコルを実装したツールサービスプロセスで、GitHub やデータベースなど呼び出し可能なツール機能を AI Agent に公開します。",
    "Provider": "モデルプロバイダー。Lurus API、OpenAI、Anthropic、Ollama などを指します。Switch は複数の Provider を設定しルールに従ってルーティングできます。",
    "CLAUDE.md": "プロジェクトのルートディレクトリに置く指示ファイルで、AI コーディングツールがこれを読み取りプロジェクトの文脈・コーディング規約・ワークフローを把握します。",
    "Proxy": "プロキシ。Switch がローカルで起動する OpenAI 互換 API エンドポイントで、リクエストをルーティングルールに従って異なる Provider へ転送します。",
    "SM4-GCM": "国家暗号 SM4 ブロック暗号 + GCM 認証付き暗号化モードで、国産暗号のコンプライアンスが求められる場面で対称暗号の第一候補となります。",
    "TCO": "総所有コスト（Total Cost of Ownership）。調達の意思決定において、ライセンス / デプロイ / 運用 / 移行までの全工程のコストを網羅します。",
    "Whisper": "OpenAI がオープンソース公開した音声認識モデルで、Creator / Lumen が音声の書き起こしに使用します。",
    "Dependency Guardian": "Forge が計画中の依存関係センチネルで、Epic / Story をまたぐインターフェースの破壊を自動検出します。",
    "Session": "Forge における一度のプロダクト議論のコンテキストコンテナで、対話・意思決定・Agent の成果物からなる完全なタイムラインを保持します。"
  },
  "ko": {
    "API Key": "API에 접근하기 위한 비밀 자격 증명으로, 비밀번호와 유사합니다. 각 Key마다 할당량과 권한을 개별 설정할 수 있습니다.",
    "Bearer Token": "HTTP 인증 방식의 하나로, 요청 헤더에 \"Bearer sk-xxx\" 형식으로 자격 증명을 담아 전달합니다.",
    "Rate Limit": "속도 제한으로, API가 단위 시간당 요청 횟수의 상한을 제어하여 남용과 과부하를 방지합니다.",
    "Streaming": "스트리밍 응답으로, AI 모델이 전체 생성을 기다리지 않고 결과를 Token 단위로 반환하여 첫 글자 지연을 줄입니다.",
    "Token": "LLM이 텍스트를 처리하는 최소 단위입니다. 중국어는 약 1.5자/token, 영어는 약 4자/token입니다.",
    "Webhook": "서버가 결제 성공, 구독 만료 등 이벤트 알림을 지정한 URL로 능동적으로 푸시하는 방식입니다.",
    "SDK": "소프트웨어 개발 키트로, 캡슐화된 함수와 클래스를 제공하여 API 호출을 단순화합니다. Lurus는 OpenAI SDK와 호환됩니다.",
    "Endpoint": "API 엔드포인트로, /v1/chat/completions와 같이 호출 가능한 URL 경로입니다.",
    "Base URL": "API의 루트 주소입니다. Lurus의 Base URL은 https://api.lurus.cn/v1입니다.",
    "GitOps": "Git 저장소를 배포의 진실 원천으로 삼아, ArgoCD 같은 자동화 도구로 원하는 상태를 클러스터에 동기화하는 방식입니다.",
    "ArgoCD": "Kubernetes용 GitOps 지속 배포 도구로, Git 저장소 변경을 감지해 클러스터에 자동 동기화합니다.",
    "OpenTelemetry": "가관측성 분야의 오픈 표준으로, Trace / Metric / Log 세 가지 신호의 수집과 전송을 통일합니다.",
    "OpenAPI": "REST API를 기술하는 개방형 명세(구 Swagger)입니다. Lurus의 데이터 구조는 게이트웨이 OpenAPI 명세에서 자동 동기화되어 생성됩니다.",
    "Schema": "데이터 구조 정의로, 요청 / 응답의 각 필드 이름, 타입, 필수 여부를 규정합니다.",
    "OIDC": "OpenID Connect로, OAuth 2.0 기반의 ID 인증 표준이며 Lurus는 Casdoor로 구현합니다.",
    "Passkey": "WebAuthn 표준 기반의 비밀번호 없는 인증 방식으로, 기기 지문 / Face ID / 보안 키로 완료됩니다.",
    "MFA": "다중 인증으로, 2가지 이상의 자격 증명을 동시에 요구합니다(비밀번호 + TOTP, 비밀번호 + Passkey 등).",
    "PAT": "Personal Access Token으로, 사용자가 생성하는 장기 API 접근 토큰이며 자동화에서 비밀번호를 대체합니다.",
    "JWT": "JSON Web Token으로, 자체 포함된 서명 토큰이며 서버가 DB 조회 없이 신원을 검증할 수 있습니다.",
    "Casdoor": "Lurus가 사용하는 오픈소스 ID 플랫폼으로, OIDC / OAuth2 / SAML / SCIM / MFA 기능을 제공합니다.",
    "SSO 联邦": "기업이 자사 IdP(Okta / Azure AD 등)를 Lurus Auth에 연동하여, 직원이 회사 계정으로 Lurus 제품에 로그인하는 방식입니다.",
    "WAL": "Write-Ahead Log, 즉 사전 기록 로그입니다. 모든 상태 변경을 실행 전에 먼저 로그에 기록하여 크래시 후 로그에서 복구할 수 있게 합니다.",
    "Checkpoint": "체크포인트로, 메모리의 전체 상태 스냅샷을 디스크에 기록합니다. 크래시 복구 시 가장 최근 Checkpoint부터 WAL을 재생합니다.",
    "CheckpointSaver": "LangGraph에서 그래프 상태의 영속화를 담당하는 컴포넌트 인터페이스로, Kova/Lumen이 제공하는 구현으로 교체할 수 있습니다.",
    "Agent": "LLM이 구동하는 자율 의사결정 프로그램으로, 입력 감지 → 추론 → 도구 호출 → 결과 산출의 흐름을 따릅니다.",
    "Agent Loop": "Agent의 의사결정 루프로, 입력 수신 → LLM 추론 → 도구 호출 → 결과 획득 → 추론 지속을 최종 답변 생성 시까지 반복합니다.",
    "Durable Execution": "지속 실행으로, 작업 상태를 계속 WAL에 기록하여 프로세스 크래시 후 중단 지점에서 자동 복구하며 LLM을 중복 호출하지 않습니다.",
    "MCP": "Model Context Protocol, 즉 모델 컨텍스트 프로토콜입니다. AI Agent가 외부 도구와 데이터 소스를 통일된 방식으로 호출하게 하는 개방형 표준입니다.",
    "A2A": "Agent-to-Agent 프로토콜로, 여러 Agent가 직접 통신하고 작업을 위임하며 정보를 교환하게 합니다.",
    "Swarm": "집단 지성 모드로, 여러 Agent가 조정자의 작업 분배에 따라 자율 협력하며 사전 정의된 고정 프로세스가 필요 없습니다.",
    "Ring Buffer": "링 버퍼로, 고정 크기의 순환 저장 구조입니다. 쓰기 포인터가 끝에 도달하면 되돌아와 오래된 데이터를 덮어쓰며, WAL은 2의 거듭제곱 크기의 링 버퍼를 사용합니다.",
    "CRC32": "순환 중복 검사 알고리즘으로, 데이터 전송이나 저장 중의 오류를 탐지하는 데 사용됩니다. Kova의 모든 WAL 레코드에는 CRC32 체크섬이 포함됩니다.",
    "FIFO": "First In, First Out, 즉 선입선출 큐입니다. Kova의 작업 스케줄링은 기본적으로 FIFO 전략을 사용합니다.",
    "System Prompt": "시스템 프롬프트로, AI의 역할, 능력 경계, 행동 규범을 정의합니다. 메시지 배열의 첫 번째에 배치됩니다.",
    "Tool Call": "AI 모델이 추론 과정에서 검색이나 데이터베이스 조회 같은 외부 도구의 호출을 결정하고, 구조화된 호출 파라미터를 반환하는 것입니다.",
    "Replay": "리플레이로, 영속화된 이벤트 시퀀스를 사용해 Agent 실행 과정을 재현하며, 로컬 디버깅 시 추가 LLM Token을 소비하지 않습니다.",
    "ACE": "Adaptive Context Engine, 즉 적응형 컨텍스트 엔진입니다. MemX의 핵심 지능 계층으로, 지식 증류, 중복 제거, 감쇠, 검색의 네 가지 모듈을 포함합니다.",
    "Embedding": "임베딩 벡터로, 텍스트를 고차원 수치 벡터로 변환하여 의미적으로 유사한 텍스트가 벡터 공간에서 가까운 거리에 위치하게 합니다. MemX는 로컬 ONNX 모델로 생성합니다.",
    "Vector Search": "벡터 검색으로, 쿼리 텍스트와 저장된 텍스트의 임베딩 벡터 거리를 계산하여 의미적으로 가장 관련성 높은 결과를 찾습니다.",
    "Semantic Dedup": "의미 기반 중복 제거로, 코사인 유사도를 통해 의미는 같지만 표현이 다른 지식 항목을 자동으로 식별하고 병합합니다.",
    "PII": "개인 식별 정보로, API Key, 비밀번호, 개인 키 등 민감 데이터를 말합니다. MemX는 우회 불가능한 12종의 PII 필터링 규칙을 내장하고 있습니다.",
    "Reflector": "MemX의 지식 증류 엔진으로, 규칙 사전 선별 + LLM 정제를 통해 대화에서 고가치 지식을 자동으로 추출합니다.",
    "Curator": "MemX의 의미 기반 중복 제거 엔진으로, 매 쓰기 시 코사인 유사도를 통해 중복 지식을 자동 병합하고 모순을 탐지합니다.",
    "Decay": "메모리 감쇠로, 인간의 망각 곡선을 모사합니다. 검색되지 않는 지식은 점차 가중치가 낮아지고, 자주 검색되는 지식은 점점 더 견고해집니다.",
    "Ebbinghaus": "에빙하우스 망각 곡선으로, 인간의 기억이 시간에 따라 지수적으로 감쇠하는 심리학 법칙입니다. MemX는 이를 바탕으로 메모리 반감기를 설계합니다.",
    "Cosine Similarity": "코사인 유사도로, 두 벡터 방향의 유사 정도를 측정하며 값의 범위는 [-1, 1]입니다. MemX는 이를 사용해 지식 중복 여부를 판단합니다(>=0.8 자동 병합).",
    "Knowledge Distillation": "지식 증류로, 대량의 대화에서 정제되고 재사용 가능한 지식 항목을 추출합니다. MemX의 Reflector 엔진이 이 과정을 자동으로 수행합니다.",
    "Ontology": "온톨로지로, 트리 구조로 도메인 지식(사용자 스토리 / 아키텍처 / 기술 스택 / 규범)을 기술합니다. Forge의 핵심 데이터 모델입니다.",
    "Backtest": "백테스트로, 과거 시세 데이터를 사용해 전략 거래를 시뮬레이션하여 과거 시장 환경에서 전략의 성과를 평가합니다.",
    "Sharpe Ratio": "샤프 지수로, 단위 위험을 감수할 때 얻는 초과 수익입니다. > 1.0이면 우수, > 2.0이면 탁월합니다.",
    "Max Drawdown": "최대 낙폭으로, 역사적 고점에서 최저점까지의 최대 하락률 백분율입니다. < 20%이면 수용 가능, < 10%이면 우수합니다.",
    "Stop Loss": "손절매로, 사전 설정한 손실 임계값에 도달하면 자동으로 청산하여 손실을 통제합니다. 리스크 관리의 기본 수단입니다.",
    "Adjustment": "수정주가로, 주식의 과거 가격에 배당/유상증자 조정을 가하여 서로 다른 시기의 가격을 비교 가능하게 합니다. 전수정과 후수정으로 나뉩니다.",
    "Round Lot": "단주/주문 단위로, A주의 최소 거래 단위이며 1단위 = 100주입니다. 매수는 반드시 단위의 정수 배수여야 합니다.",
    "Commission": "수수료로, 증권사가 거래마다 부과하는 비용입니다. A주는 일반적으로 약 0.03% 수준이며 최저 5위안 제한이 있습니다.",
    "Stamp Duty": "인지세로, 주식 매도 시 국가가 징수하는 세금입니다. A주의 현재 세율은 거래 금액의 0.05%입니다.",
    "Slippage": "슬리피지로, 예상 체결가와 실제 체결가의 차이입니다. 대규모 자금이나 유동성이 낮은 종목일수록 슬리피지가 더 두드러집니다.",
    "Win Rate": "승률로, 수익 거래가 전체 거래 횟수에서 차지하는 비율입니다. > 50%이면 기본, > 60%이면 양호합니다.",
    "Sortino": "소르티노 지수로, 샤프 지수와 유사하지만 하방 변동성(손실 위험)만 고려하여 투자자의 실제 체감을 더 잘 반영합니다.",
    "Calmar": "칼마 지수로, 연환산 수익률 / 최대 낙폭입니다. > 1.0이면 수익이 최대 낙폭을 커버할 수 있음을 의미합니다.",
    "Decimal.js": "JavaScript의 임의 정밀도 십진 연산 라이브러리로, Lucrum은 이를 사용해 금융 계산에서의 부동소수점 오차를 제거합니다.",
    "CtaTemplate": "vnpy의 전략 템플릿 기반 클래스로, 표준적인 on_bar / on_tick / on_trade 등 생명주기 후크를 정의합니다.",
    "vnpy": "Python 퀀트 트레이딩 오픈소스 프레임워크로, Lucrum AI가 생성하는 전략 코드는 vnpy CtaTemplate을 기반으로 합니다.",
    "鹿贝": "Lurus 플랫폼의 통합 과금 단위(Lubei)입니다. 모든 제품 소비는 Lubei로 차감되며, 1 Lubei = 1센트 상당입니다.",
    "MCP Server": "MCP 프로토콜을 구현한 도구 서비스 프로세스로, AI Agent에게 GitHub, 데이터베이스 등 호출 가능한 도구 기능을 노출합니다.",
    "Provider": "모델 제공자로, Lurus API, OpenAI, Anthropic, Ollama 등을 말합니다. Switch는 여러 Provider 설정과 규칙 기반 라우팅을 지원합니다.",
    "CLAUDE.md": "프로젝트 루트 디렉터리에 두는 지시 파일로, AI 코딩 도구가 이를 읽어 프로젝트 컨텍스트, 코딩 규범, 워크플로우를 이해합니다.",
    "Proxy": "프록시로, Switch가 로컬에서 시작하는 OpenAI 호환 API 엔드포인트이며, 요청을 라우팅 규칙에 따라 서로 다른 Provider로 전달합니다.",
    "SM4-GCM": "국산 암호 SM4 블록 암호 + GCM 인증 암호화 모드로, 국산 암호 규정 준수가 필요한 시나리오에서 대칭 암호화의 우선 선택지입니다.",
    "TCO": "총소유비용(Total Cost of Ownership)으로, 구매 결정에서 라이선스 / 배포 / 운영 / 마이그레이션을 아우르는 전 과정 비용입니다.",
    "Whisper": "OpenAI가 공개한 음성 인식 모델로, Creator / Lumen이 이를 사용해 오디오를 텍스트로 변환합니다.",
    "Dependency Guardian": "Forge가 기획 중인 의존 관계 감시자로, Epic / Story 간 인터페이스 파손을 자동으로 탐지합니다.",
    "Session": "Forge에서 한 차례의 제품 논의에 대한 컨텍스트 컨테이너로, 대화, 의사결정, Agent 산출물의 전체 타임라인을 담습니다."
  },
  "es": {
    "API Key": "Credencial de acceso a la API, similar a una contraseña. Cada Key puede tener cuotas y permisos configurados de forma independiente.",
    "Bearer Token": "Un método de autenticación HTTP que transporta la credencial en la cabecera de la solicitud con el formato \"Bearer sk-xxx\".",
    "Rate Limit": "Límite de velocidad: control del número máximo de solicitudes que la API admite por unidad de tiempo, para evitar el abuso y la sobrecarga.",
    "Streaming": "Respuesta en streaming: el modelo de IA devuelve el resultado token a token (en lugar de esperar a generarlo por completo), reduciendo la latencia del primer carácter.",
    "Token": "La unidad mínima con la que un LLM procesa el texto. En chino, aproximadamente 1,5 caracteres/token; en inglés, aproximadamente 4 caracteres/token.",
    "Webhook": "El servidor envía de forma proactiva notificaciones de eventos a la URL que indiques, como un pago correcto o el vencimiento de una suscripción.",
    "SDK": "Kit de desarrollo de software que ofrece funciones y clases ya encapsuladas para simplificar las llamadas a la API. Lurus es compatible con el SDK de OpenAI.",
    "Endpoint": "Endpoint de la API: una ruta de URL invocable, como /v1/chat/completions.",
    "Base URL": "La dirección raíz de la API. La Base URL de Lurus es https://api.lurus.cn/v1.",
    "GitOps": "Usa un repositorio Git como fuente de verdad del despliegue y, mediante herramientas de automatización (como ArgoCD), sincroniza el estado deseado con el clúster.",
    "ArgoCD": "Herramienta de entrega continua GitOps para Kubernetes que observa los cambios en el repositorio Git y los sincroniza automáticamente con el clúster.",
    "OpenTelemetry": "Estándar de código abierto en el ámbito de la observabilidad que unifica la recopilación y el transporte de las tres señales principales: Trace / Metric / Log.",
    "OpenAPI": "Especificación abierta que describe las REST API (antes Swagger). Las estructuras de datos de Lurus se generan y sincronizan automáticamente a partir de la especificación OpenAPI del gateway.",
    "Schema": "Definición de la estructura de datos que determina el nombre, el tipo y la obligatoriedad de cada campo en la solicitud y la respuesta.",
    "OIDC": "OpenID Connect, un estándar de autenticación de identidad basado en OAuth 2.0. Lurus lo implementa con Casdoor.",
    "Passkey": "Método de autenticación sin contraseña basado en el estándar WebAuthn, completado mediante la huella del dispositivo, Face ID o una clave de seguridad.",
    "MFA": "Autenticación multifactor que exige aportar simultáneamente 2 o más credenciales (contraseña + TOTP, contraseña + Passkey, etc.).",
    "PAT": "Personal Access Token: token de acceso a la API de larga duración generado por el usuario, que sustituye a la contraseña para la automatización.",
    "JWT": "JSON Web Token: token firmado y autocontenido que el servidor puede verificar sin necesidad de consultar la base de datos.",
    "Casdoor": "Plataforma de identidad de código abierto que utiliza Lurus, con capacidades de OIDC / OAuth2 / SAML / SCIM / MFA.",
    "SSO 联邦": "La empresa conecta su propio IdP (Okta, Azure AD, etc.) a Lurus Auth para que los empleados inicien sesión en los productos de Lurus con su cuenta corporativa.",
    "WAL": "Write-Ahead Log (registro de escritura anticipada). Todo cambio de estado se escribe primero en el registro y luego se ejecuta, garantizando la recuperación desde el registro tras un fallo.",
    "Checkpoint": "Punto de control: instantánea completa del estado en memoria escrita en disco. En la recuperación ante fallos se reproduce el WAL a partir del Checkpoint más reciente.",
    "CheckpointSaver": "La interfaz del componente de LangGraph encargado de persistir el estado del grafo, que puede sustituirse por la implementación que ofrecen Kova/Lumen.",
    "Agent": "Programa autónomo de toma de decisiones impulsado por un LLM: percibe la entrada → razona → invoca herramientas → produce un resultado.",
    "Agent Loop": "Ciclo de decisión del agente: recibe la entrada → el LLM razona → invoca herramientas → obtiene el resultado → sigue razonando, hasta generar la respuesta final.",
    "Durable Execution": "Ejecución persistente: el estado de la tarea se escribe continuamente en el WAL y, tras un fallo del proceso, se reanuda automáticamente desde el punto de interrupción sin volver a invocar el LLM.",
    "MCP": "Model Context Protocol (protocolo de contexto de modelo). Un estándar abierto que permite a los agentes de IA invocar herramientas y fuentes de datos externas de forma unificada.",
    "A2A": "Protocolo Agent-to-Agent que permite que varios agentes se comuniquen directamente, deleguen tareas e intercambien información.",
    "Swarm": "Modo de inteligencia colectiva en el que un coordinador asigna tareas a varios agentes que colaboran de forma autónoma, sin un flujo fijo predefinido.",
    "Ring Buffer": "Búfer circular: estructura de almacenamiento cíclica de tamaño fijo. Cuando el puntero de escritura llega al final, vuelve al inicio y sobrescribe los datos antiguos; el WAL usa un búfer circular de tamaño potencia de 2.",
    "CRC32": "Algoritmo de comprobación de redundancia cíclica que detecta errores en la transmisión o el almacenamiento de datos. Cada registro del WAL de Kova incluye una suma de comprobación CRC32.",
    "FIFO": "First In, First Out (cola de primero en entrar, primero en salir). La planificación de tareas de Kova usa la estrategia FIFO de forma predeterminada.",
    "System Prompt": "Prompt del sistema que define el rol, los límites de capacidad y las normas de comportamiento de la IA. Se coloca como primer elemento del array de mensajes.",
    "Tool Call": "Durante el razonamiento, el modelo de IA decide invocar una herramienta externa (como una búsqueda o una consulta a la base de datos) y devuelve parámetros de llamada estructurados.",
    "Replay": "Reproducción: usa la secuencia de eventos ya persistida para reproducir el proceso de ejecución del agente; la depuración local no consume tokens adicionales del LLM.",
    "ACE": "Adaptive Context Engine (motor de contexto adaptativo). La capa de inteligencia central de MemX, que incluye cuatro módulos: destilación de conocimiento, deduplicación, decaimiento y recuperación.",
    "Embedding": "Vector de incrustación: convierte el texto en un vector numérico de alta dimensión, de modo que los textos semánticamente similares queden próximos en el espacio vectorial. MemX los genera con un modelo ONNX local.",
    "Vector Search": "Búsqueda vectorial: encuentra los resultados más relevantes semánticamente calculando la distancia entre el vector de incrustación del texto de consulta y los textos almacenados.",
    "Semantic Dedup": "Deduplicación semántica: mediante la similitud del coseno, identifica y fusiona automáticamente las entradas de conocimiento con el mismo significado pero distinta redacción.",
    "PII": "Información de identificación personal, como API Key, contraseñas o claves privadas y otros datos sensibles. MemX incorpora 12 reglas de filtrado de PII que no se pueden eludir.",
    "Reflector": "El motor de destilación de conocimiento de MemX, que extrae automáticamente conocimiento de alto valor de las conversaciones mediante un prefiltrado por reglas y un refinamiento con LLM.",
    "Curator": "El motor de deduplicación semántica de MemX que, en cada escritura, fusiona automáticamente el conocimiento duplicado y detecta contradicciones mediante la similitud del coseno.",
    "Decay": "Decaimiento de la memoria: simula la curva del olvido humano. El conocimiento que no se recupera reduce su peso gradualmente, mientras que el que se recupera con frecuencia se afianza cada vez más.",
    "Ebbinghaus": "Curva del olvido de Ebbinghaus: la ley psicológica según la cual la memoria humana decae de forma exponencial con el tiempo. MemX diseña la semivida de la memoria a partir de ella.",
    "Cosine Similarity": "Similitud del coseno: mide cuán parecidas son las direcciones de dos vectores, con un rango de valores de [-1, 1]. MemX la usa para decidir si un conocimiento está duplicado (>=0,8 se fusiona automáticamente).",
    "Knowledge Distillation": "Destilación de conocimiento: extrae de un gran volumen de conversaciones entradas de conocimiento depuradas y reutilizables. El motor Reflector de MemX realiza este proceso automáticamente.",
    "Ontology": "Ontología: describe el conocimiento del dominio con una estructura en árbol (historias de usuario / arquitectura / stack tecnológico / normas). Es el modelo de datos central de Forge.",
    "Backtest": "Backtest: usa datos históricos del mercado para simular las operaciones de una estrategia y evaluar su rendimiento en el entorno de mercado del pasado.",
    "Sharpe Ratio": "Ratio de Sharpe: el exceso de rentabilidad obtenido por cada unidad de riesgo asumido. > 1,0 es excelente, > 2,0 es excepcional.",
    "Max Drawdown": "Máxima caída (drawdown): el porcentaje de descenso máximo desde el punto histórico más alto hasta el más bajo. < 20% es aceptable, < 10% es excelente.",
    "Stop Loss": "Stop loss: umbral de pérdida predefinido que, al alcanzarse, cierra la posición automáticamente para limitar las pérdidas. Es la herramienta básica de control de riesgo.",
    "Adjustment": "Ajuste de precios: corrige los precios históricos de una acción por dividendos o emisiones de acciones para que los precios de distintos periodos sean comparables. Se divide en ajuste anterior y posterior.",
    "Round Lot": "Lote estándar: la unidad mínima de negociación en las acciones A, donde 1 lote = 100 acciones. La compra debe ser un múltiplo entero de lotes.",
    "Commission": "Comisión: la tarifa que el bróker cobra por cada operación. En las acciones A suele rondar el 0,03% (tres por diez mil), con un mínimo de 5 yuanes.",
    "Stamp Duty": "Impuesto de timbre: tasa que el Estado recauda al vender acciones. El tipo actual en las acciones A es del 0,05% (cinco por diez mil) del importe de la operación.",
    "Slippage": "Deslizamiento (slippage): la diferencia entre el precio de ejecución esperado y el real. Es más acusado con grandes capitales o activos de baja liquidez.",
    "Win Rate": "Tasa de aciertos: la proporción de operaciones rentables sobre el total de operaciones. > 50% es lo básico, > 60% es bueno.",
    "Sortino": "Ratio de Sortino: similar al ratio de Sharpe, pero solo considera la volatilidad a la baja (el riesgo de pérdida), por lo que refleja mejor la experiencia real del inversor.",
    "Calmar": "Ratio de Calmar: rentabilidad anualizada / máxima caída. > 1,0 indica que la rentabilidad puede cubrir la máxima caída.",
    "Decimal.js": "Biblioteca de JavaScript para cálculos decimales de precisión arbitraria que Lucrum usa para eliminar los errores de coma flotante en los cálculos financieros.",
    "CtaTemplate": "La clase base de plantillas de estrategia de vnpy, que define los hooks de ciclo de vida estándar como on_bar / on_tick / on_trade.",
    "vnpy": "Framework de código abierto de trading cuantitativo en Python. El código de estrategia que genera la IA de Lucrum se basa en CtaTemplate de vnpy.",
    "鹿贝": "La unidad de facturación unificada de la plataforma Lurus (Lubei). Todo el consumo de los productos se cobra en Lubei; 1 Lubei equivale a 1 centavo de dólar.",
    "MCP Server": "Proceso de servicio de herramientas que implementa el protocolo MCP y expone capacidades de herramientas invocables a los agentes de IA (como GitHub, bases de datos, etc.).",
    "Provider": "Proveedor de modelos, como Lurus API, OpenAI, Anthropic u Ollama. Switch permite configurar varios Provider y enrutar según reglas.",
    "CLAUDE.md": "Archivo de instrucciones colocado en el directorio raíz del proyecto que las herramientas de programación con IA leen para entender el contexto del proyecto, las normas de codificación y el flujo de trabajo.",
    "Proxy": "Proxy: un endpoint de API compatible con OpenAI que Switch arranca localmente y que reenvía las solicitudes a distintos Provider según las reglas de enrutamiento.",
    "SM4-GCM": "Cifrado de bloques SM4 del estándar criptográfico chino + modo de cifrado autenticado GCM, la opción preferida de cifrado simétrico en escenarios de cumplimiento de la criptografía nacional china.",
    "TCO": "Coste total de propiedad (Total Cost of Ownership): en las decisiones de compra, abarca el coste de extremo a extremo de licencias, despliegue, operación y migración.",
    "Whisper": "Modelo de reconocimiento de voz de código abierto de OpenAI que Creator y Lumen utilizan para la transcripción de audio.",
    "Dependency Guardian": "El centinela de dependencias previsto en Forge, que detecta automáticamente las rupturas de interfaces entre Epics y Stories.",
    "Session": "En Forge, el contenedor de contexto de una sesión de discusión de producto, que recoge la línea de tiempo completa de la conversación, las decisiones y los resultados del agente."
  },
  "fr": {
    "API Key": "Identifiant secret permettant d'accéder à l'API, semblable à un mot de passe. Chaque Key peut avoir ses propres quotas et permissions.",
    "Bearer Token": "Méthode d'authentification HTTP qui transporte l'identifiant dans l'en-tête de requête au format \"Bearer sk-xxx\".",
    "Rate Limit": "Limitation de débit : plafond imposé par l'API au nombre de requêtes par unité de temps, pour prévenir les abus et la surcharge.",
    "Streaming": "Réponse en flux : le modèle d'IA renvoie le résultat token par token (au lieu d'attendre la génération complète), ce qui réduit la latence du premier caractère.",
    "Token": "Unité la plus petite que le LLM utilise pour traiter le texte. Environ 1,5 caractère/token pour le chinois, 4 caractères/token pour l'anglais.",
    "Webhook": "Notification d'événement que le serveur envoie spontanément à l'URL que vous indiquez, par exemple un paiement réussi ou l'expiration d'un abonnement.",
    "SDK": "Kit de développement logiciel fournissant des fonctions et classes prêtes à l'emploi pour simplifier les appels à l'API. Lurus est compatible avec le SDK OpenAI.",
    "Endpoint": "Endpoint d'API : un chemin d'URL appelable, par exemple /v1/chat/completions.",
    "Base URL": "Adresse racine de l'API. La Base URL de Lurus est https://api.lurus.cn/v1.",
    "GitOps": "Pratique utilisant un dépôt Git comme source de vérité du déploiement, des outils automatisés (comme ArgoCD) synchronisant l'état souhaité vers le cluster.",
    "ArgoCD": "Outil de livraison continue GitOps pour Kubernetes, qui surveille les changements du dépôt Git et les synchronise automatiquement vers le cluster.",
    "OpenTelemetry": "Standard open source de l'observabilité, qui unifie la collecte et le transport des trois signaux Trace / Metric / Log.",
    "OpenAPI": "Spécification ouverte décrivant les API REST (anciennement Swagger). Les structures de données de Lurus sont générées automatiquement à partir de la spécification OpenAPI de la passerelle.",
    "Schema": "Définition d'une structure de données précisant le nom, le type et le caractère obligatoire de chaque champ d'une requête ou réponse.",
    "OIDC": "OpenID Connect, standard d'authentification d'identité fondé sur OAuth 2.0 ; Lurus l'implémente avec Casdoor.",
    "Passkey": "Méthode d'authentification sans mot de passe fondée sur le standard WebAuthn, réalisée via l'empreinte de l'appareil, Face ID ou une clé de sécurité.",
    "MFA": "Authentification multifacteur, qui exige la présentation simultanée de 2 facteurs ou plus (mot de passe + TOTP, mot de passe + Passkey, etc.).",
    "PAT": "Personal Access Token : jeton d'accès API de longue durée généré par l'utilisateur, qui remplace le mot de passe pour l'automatisation.",
    "JWT": "JSON Web Token : jeton signé autoporteur que le serveur peut vérifier sans interroger la base de données.",
    "Casdoor": "Plateforme d'identité open source utilisée par Lurus, offrant les capacités OIDC / OAuth2 / SAML / SCIM / MFA.",
    "SSO 联邦": "Fédération SSO : une entreprise raccorde son propre IdP (Okta, Azure AD, etc.) à Lurus Auth, et ses employés se connectent aux produits Lurus avec leur compte d'entreprise.",
    "WAL": "Write-Ahead Log (journal d'écriture anticipée). Tout changement d'état est d'abord écrit dans le journal puis exécuté, garantissant une reprise après crash à partir du journal.",
    "Checkpoint": "Point de contrôle : un instantané complet de l'état en mémoire écrit sur disque. Lors d'une reprise après crash, le rejeu du WAL repart du Checkpoint le plus récent.",
    "CheckpointSaver": "Interface du composant de LangGraph chargé de persister l'état du graphe, remplaçable par les implémentations fournies par Kova/Lumen.",
    "Agent": "Programme de décision autonome piloté par un LLM : perception de l'entrée → raisonnement → appel d'outils → production d'un résultat.",
    "Agent Loop": "Boucle de décision de l'agent : réception de l'entrée → raisonnement du LLM → appel d'outils → récupération du résultat → poursuite du raisonnement, jusqu'à la réponse finale.",
    "Durable Execution": "Exécution persistante : l'état de la tâche est écrit en continu dans le WAL, de sorte qu'après un crash du processus la reprise se fait automatiquement au point d'interruption, sans rappeler le LLM.",
    "MCP": "Model Context Protocol (protocole de contexte des modèles). Standard ouvert permettant aux agents IA d'appeler des outils et sources de données externes de façon unifiée.",
    "A2A": "Protocole Agent-to-Agent, qui permet à plusieurs agents de communiquer directement, de déléguer des tâches et d'échanger des informations.",
    "Swarm": "Mode d'intelligence collective où plusieurs agents reçoivent leurs tâches d'un coordinateur et collaborent de façon autonome, sans flux fixe prédéfini.",
    "Ring Buffer": "Tampon circulaire : structure de stockage cyclique de taille fixe. Lorsque le pointeur d'écriture atteint la fin, il revient au début et écrase les anciennes données ; le WAL utilise un tampon circulaire de taille en puissance de 2.",
    "CRC32": "Algorithme de contrôle de redondance cyclique, utilisé pour détecter les erreurs lors de la transmission ou du stockage des données. Chaque enregistrement WAL de Kova contient une somme de contrôle CRC32.",
    "FIFO": "First In, First Out : file premier entré, premier sorti. L'ordonnancement des tâches de Kova utilise par défaut la stratégie FIFO.",
    "System Prompt": "Invite système qui définit le rôle, les limites de capacité et les règles de comportement de l'IA. Elle est placée en première position du tableau de messages.",
    "Tool Call": "Lorsque, durant son raisonnement, le modèle d'IA décide d'appeler un outil externe (recherche, requête de base de données, etc.) et renvoie des paramètres d'appel structurés.",
    "Replay": "Rejeu : reproduction de l'exécution d'un agent à partir de la séquence d'événements déjà persistée, pour un débogage local qui ne consomme pas de tokens LLM supplémentaires.",
    "ACE": "Adaptive Context Engine (moteur de contexte adaptatif). Couche d'intelligence centrale de MemX, comprenant quatre modules : distillation des connaissances, déduplication, décroissance et recherche.",
    "Embedding": "Vecteur d'embedding : conversion d'un texte en un vecteur numérique de haute dimension, qui rapproche dans l'espace vectoriel les textes sémantiquement proches. MemX les génère avec un modèle ONNX local.",
    "Vector Search": "Recherche vectorielle : on trouve les résultats les plus proches sémantiquement en calculant la distance entre le vecteur d'embedding du texte de requête et ceux des textes stockés.",
    "Semantic Dedup": "Déduplication sémantique : identification et fusion automatiques, par similarité cosinus, des entrées de connaissance de même sens mais formulées différemment.",
    "PII": "Informations personnelles identifiables, telles qu'une API Key, un mot de passe ou une clé privée. MemX intègre 12 règles de filtrage PII incontournables.",
    "Reflector": "Moteur de distillation des connaissances de MemX, qui extrait automatiquement les connaissances à forte valeur des conversations par préfiltrage à base de règles puis raffinement par LLM.",
    "Curator": "Moteur de déduplication sémantique de MemX, qui fusionne automatiquement les connaissances redondantes par similarité cosinus et détecte les contradictions à chaque écriture.",
    "Decay": "Décroissance de la mémoire, qui imite la courbe d'oubli humaine. Les connaissances jamais recherchées voient leur poids diminuer progressivement, tandis que celles souvent recherchées se consolident.",
    "Ebbinghaus": "Courbe d'oubli d'Ebbinghaus : loi psychologique selon laquelle la mémoire humaine décroît exponentiellement avec le temps. MemX s'en inspire pour concevoir la demi-vie de la mémoire.",
    "Cosine Similarity": "Similarité cosinus : mesure du degré de similarité d'orientation entre deux vecteurs, dans l'intervalle [-1, 1]. MemX l'utilise pour déterminer si une connaissance est redondante (fusion automatique à partir de 0,8).",
    "Knowledge Distillation": "Distillation des connaissances : extraction d'entrées de connaissance affinées et réutilisables à partir d'un grand volume de conversations. Le moteur Reflector de MemX réalise ce processus automatiquement.",
    "Ontology": "Ontologie : description des connaissances d'un domaine sous forme d'arborescence (récits utilisateurs / architecture / pile technique / normes). C'est le modèle de données central de Forge.",
    "Backtest": "Backtesting : simulation des transactions d'une stratégie sur des données de marché historiques afin d'évaluer ses performances dans les conditions de marché passées.",
    "Sharpe Ratio": "Ratio de Sharpe : rendement excédentaire obtenu par unité de risque supportée. > 1,0 : excellent ; > 2,0 : exceptionnel.",
    "Max Drawdown": "Drawdown maximal : baisse maximale en pourcentage entre un sommet historique et le creux qui suit. < 20 % : acceptable ; < 10 % : excellent.",
    "Stop Loss": "Stop loss : seuil de perte prédéfini qui déclenche automatiquement la clôture de la position pour limiter les pertes. C'est un instrument de base de la gestion des risques.",
    "Adjustment": "Ajustement : correction des prix historiques d'une action pour tenir compte des dividendes et émissions d'actions, afin de rendre comparables les prix de différentes périodes. On distingue l'ajustement antérieur et l'ajustement postérieur.",
    "Round Lot": "Lot : unité minimale de transaction des actions A, 1 lot = 100 actions. Les achats doivent être un multiple entier d'un lot.",
    "Commission": "Commission : frais prélevés par le courtier sur chaque transaction. Sur le marché des actions A, le taux est d'environ 0,03 %, avec un minimum de 5 yuans.",
    "Stamp Duty": "Droit de timbre : taxe perçue par l'État lors de la vente d'actions. Sur le marché des actions A, le taux actuel est de 0,05 % du montant de la transaction.",
    "Slippage": "Slippage : écart entre le prix d'exécution attendu et le prix d'exécution réel. Il est plus marqué pour les gros volumes ou les titres peu liquides.",
    "Win Rate": "Taux de réussite : proportion de transactions gagnantes sur le nombre total de transactions. > 50 % : correct ; > 60 % : bon.",
    "Sortino": "Ratio de Sortino : semblable au ratio de Sharpe, mais ne prend en compte que la volatilité à la baisse (le risque de perte), ce qui reflète mieux l'expérience réelle de l'investisseur.",
    "Calmar": "Ratio de Calmar : rendement annualisé / drawdown maximal. > 1,0 signifie que le rendement couvre le drawdown maximal.",
    "Decimal.js": "Bibliothèque JavaScript de calcul décimal à précision arbitraire, que Lucrum utilise pour éliminer les erreurs de virgule flottante dans les calculs financiers.",
    "CtaTemplate": "Classe de base des modèles de stratégie de vnpy, qui définit les hooks de cycle de vie standard on_bar / on_tick / on_trade, etc.",
    "vnpy": "Framework open source de trading quantitatif en Python ; le code de stratégie généré par l'IA de Lucrum repose sur le CtaTemplate de vnpy.",
    "鹿贝": "Unité de facturation unifiée de la plateforme Lurus (Lubei). Toute consommation de produit est débitée en Lubei, 1 Lubei équivalant à 1 cent de dollar.",
    "MCP Server": "Processus de service d'outils implémentant le protocole MCP, qui expose aux agents IA des capacités d'outils appelables (GitHub, base de données, etc.).",
    "Provider": "Fournisseur de modèles, tel que Lurus API, OpenAI, Anthropic ou Ollama. Switch permet de configurer plusieurs Provider et de router selon des règles.",
    "CLAUDE.md": "Fichier d'instructions placé à la racine du projet, que les outils de programmation IA lisent pour comprendre le contexte du projet, les normes de codage et le flux de travail.",
    "Proxy": "Proxy : endpoint d'API compatible OpenAI que Switch lance en local et qui transmet les requêtes à différents Provider selon les règles de routage.",
    "SM4-GCM": "Chiffrement par bloc SM4 (cryptographie nationale chinoise) en mode d'authentification GCM, premier choix de chiffrement symétrique dans les contextes de conformité cryptographique chinoise.",
    "TCO": "Coût total de possession (Total Cost of Ownership) : dans une décision d'achat, il couvre la totalité des coûts — licences, déploiement, exploitation et migration.",
    "Whisper": "Modèle de reconnaissance vocale open source d'OpenAI, que Creator / Lumen utilisent pour la transcription audio.",
    "Dependency Guardian": "Sentinelle des dépendances prévue dans Forge, qui détecte automatiquement les ruptures d'interface entre Epic et Story.",
    "Session": "Dans Forge, conteneur de contexte d'une discussion produit, qui porte la chronologie complète des conversations, décisions et productions de l'agent."
  }
}

export const uiTr: Record<Locale, UiTr> = {
  "en": {
    "hero": {
      "title": "AI Infrastructure and Product Platform",
      "taglineLead": "Not just another layer of SaaS.",
      "taglineAccent": "Execution, Memory, Gateway, Billing",
      "taglineTail": "useful on their own, stronger together — compose intelligence like a multi-bit screwdriver.",
      "btnStart": "Get started in 3 minutes",
      "btnKey": "Get an API Key",
      "btnConsole": "Console ↗",
      "metrics": [
        "Product Matrix",
        "AI Models Integrated",
        "Kova Scheduling Latency",
        "Free Quota"
      ]
    },
    "related": {
      "heading": "Related Products",
      "paired": "Commonly paired with",
      "referenced": "Referenced by these products"
    },
    "term": {
      "more": "Learn more →"
    }
  },
  "ja": {
    "hero": {
      "title": "AI 基盤・プロダクトプラットフォーム",
      "taglineLead": "もう一層の SaaS ではありません。",
      "taglineAccent": "実行・記憶・ゲートウェイ・課金",
      "taglineTail": "それぞれ単独でも使え、組み合わせればさらに強力に — ドライバーのビットを組み替えるように知能を組み合わせます。",
      "btnStart": "3 分で始める",
      "btnKey": "API Key を取得",
      "btnConsole": "コンソール ↗",
      "metrics": [
        "プロダクトマトリクス",
        "AI モデル接続",
        "Kova スケジューリング遅延",
        "無料枠"
      ]
    },
    "related": {
      "heading": "関連プロダクト",
      "paired": "よく一緒に使う",
      "referenced": "これらのプロダクトから参照"
    },
    "term": {
      "more": "詳しく見る →"
    }
  },
  "ko": {
    "hero": {
      "title": "AI 인프라 및 제품 플랫폼",
      "taglineLead": "또 하나의 SaaS 계층이 아닙니다.",
      "taglineAccent": "실행·기억·게이트웨이·과금",
      "taglineTail": "각각 단독으로도 쓸 수 있고, 조합하면 더 강력합니다 — 조합형 드라이버처럼 지능을 조합하세요.",
      "btnStart": "3분 만에 시작",
      "btnKey": "API Key 발급",
      "btnConsole": "콘솔 ↗",
      "metrics": [
        "제품 매트릭스",
        "AI 모델 연동",
        "Kova 스케줄링 지연",
        "무료 크레딧"
      ]
    },
    "related": {
      "heading": "관련 제품",
      "paired": "주로 함께 사용",
      "referenced": "이 제품들이 참조함"
    },
    "term": {
      "more": "더 알아보기 →"
    }
  },
  "es": {
    "hero": {
      "title": "Plataforma de infraestructura y productos de IA",
      "taglineLead": "No es otra capa de SaaS más.",
      "taglineAccent": "Ejecución, memoria, gateway, facturación",
      "taglineTail": "Cada uno funciona por sí solo y juntos son más potentes — combina inteligencia como quien combina puntas de destornillador.",
      "btnStart": "Empieza en 3 minutos",
      "btnKey": "Obtener API Key",
      "btnConsole": "Consola ↗",
      "metrics": [
        "Matriz de productos",
        "Acceso a modelos de IA",
        "Latencia de planificación de Kova",
        "Cuota gratuita"
      ]
    },
    "related": {
      "heading": "Productos relacionados",
      "paired": "Suele combinarse con",
      "referenced": "Referenciado por estos productos"
    },
    "term": {
      "more": "Más información →"
    }
  },
  "fr": {
    "hero": {
      "title": "Plateforme d'infrastructure et de produits IA",
      "taglineLead": "Pas une couche SaaS de plus.",
      "taglineAccent": "Exécution, mémoire, passerelle, facturation",
      "taglineTail": "Utilisables séparément, plus puissants combinés — composez l'intelligence comme un tournevis à embouts.",
      "btnStart": "Prise en main en 3 minutes",
      "btnKey": "Obtenir une API Key",
      "btnConsole": "Console ↗",
      "metrics": [
        "Matrice de produits",
        "Modèles d'IA intégrés",
        "Latence d'ordonnancement Kova",
        "Quota gratuit"
      ]
    },
    "related": {
      "heading": "Produits associés",
      "paired": "Souvent associé à",
      "referenced": "Référencé par ces produits"
    },
    "term": {
      "more": "En savoir plus →"
    }
  }
}
