#!/usr/bin/env bun
/**
 * build-manifest.ts — (Re)baseline the i18n translation manifest.
 *
 * For every zh source file that has at least one locale translation, records the
 * git blob SHA of the zh source AT HEAD. The checker (check-stale.ts) later
 * recomputes those SHAs and flags any whose source drifted — i.e. translations
 * that may now lag the Chinese original.
 *
 * WHY git blob SHA: git already content-addresses every file, so the baseline is
 * exact, reproducible, and free of custom hashing. HEAD (committed) is used on
 * purpose — never the working tree — so in-flight uncommitted edits from a
 * concurrent session are not frozen in as "translations match this version".
 *
 * Run this AFTER a translation sync (zh edited -> locales re-translated), then
 * commit the updated manifest alongside the translations. The manifest diff is
 * an auditable record of which pages were re-synced.
 *
 * Usage: bun scripts/i18n/build-manifest.ts
 */
import { writeFileSync } from 'fs'
import { resolve } from 'path'
import { execFileSync } from 'child_process'

const ROOT = resolve(import.meta.dir, '../..')
const MANIFEST = resolve(ROOT, 'docs/.vitepress/data/i18n-manifest.json')

/** Locale subdirectories under docs/. zh is the source-of-truth at the root. */
const LOCALES = ['en', 'ja', 'ko', 'es', 'fr'] as const

/**
 * zh source-of-truth data files whose changes invalidate the generated TS
 * overlays. products.ts / glossary.ts feed i18n-data.ts; glossary.ts /
 * models.yaml / integrations.ts feed i18n-pages-data.ts. (See scripts/i18n/README.md.)
 */
const DATA_SOURCES = [
  'docs/.vitepress/data/products.ts',
  'docs/.vitepress/data/glossary.ts',
  'docs/.vitepress/data/models.yaml',
  'docs/.vitepress/data/integrations.ts',
]

function git(args: string[]): string {
  return execFileSync('git', args, { cwd: ROOT, encoding: 'utf8' }).trim()
}

/** git blob SHA of a path at HEAD, or null if it is not tracked at HEAD. */
function blobAtHead(path: string): string | null {
  try {
    const out = git(['ls-tree', 'HEAD', '--', path])
    if (!out) return null
    const m = out.match(/^\S+\s+blob\s+(\S+)\t/)
    return m ? m[1] : null
  } catch {
    return null
  }
}

// ── Enumerate locale markdown files committed at HEAD ───────────────────────────
const localeFiles = git([
  'ls-tree', '-r', '--name-only', 'HEAD', '--',
  ...LOCALES.map((l) => `docs/${l}`),
])
  .split('\n')
  .filter((f) => f.endsWith('.md'))

// Group by the zh source each locale file translates.
const localesByZh: Record<string, Set<string>> = {}
for (const f of localeFiles) {
  const m = f.match(/^docs\/(en|ja|ko|es|fr)\/(.+)$/)
  if (!m) continue
  const [, locale, rel] = m
  const zh = `docs/${rel}`
  ;(localesByZh[zh] ??= new Set()).add(locale)
}

const pages: Record<string, { sha: string | null; locales: string[] }> = {}
let orphans = 0
for (const zh of Object.keys(localesByZh).sort()) {
  const sha = blobAtHead(zh)
  if (sha === null) orphans++
  pages[zh] = { sha, locales: [...localesByZh[zh]].sort() }
}

const dataSources: Record<string, string | null> = {}
for (const d of DATA_SOURCES) dataSources[d] = blobAtHead(d)

const manifest = {
  $schema: 'i18n-manifest/v1',
  note:
    'Generated by scripts/i18n/build-manifest.ts. SHAs are git blob hashes of the ' +
    'zh source at re-baseline time. Do not hand-edit; run `bun run i18n:manifest`.',
  locales: [...LOCALES],
  pages,
  dataSources,
}

writeFileSync(MANIFEST, JSON.stringify(manifest, null, 2) + '\n', 'utf8')

console.log(`[i18n] manifest written: ${Object.keys(pages).length} translated pages, ${DATA_SOURCES.length} data sources tracked`)
if (orphans) console.warn(`[i18n] warning: ${orphans} page(s) have locale files but no zh source at HEAD (orphans)`)
