#!/usr/bin/env bun
/**
 * sync.ts - Sync documentation from machine-readable sources.
 *
 * Sources:
 *   ../2b-svc-newapi/docs/openapi/relay.json  →  docs/api/overview.md   (endpoint region)
 *
 * Usage: bun scripts/sync.ts
 */
import { readFileSync, writeFileSync } from 'fs'
import { resolve } from 'path'
import modelsLoader from '../docs/.vitepress/data/models.data'

const ROOT = resolve(import.meta.dir, '..')
const DOCS = resolve(ROOT, 'docs')

// ── Helpers ───────────────────────────────────────────────────────────────────

/** Read a file as UTF-8, stripping BOM if present. */
function readText(filePath: string): string {
  const raw = readFileSync(filePath, 'utf8')
  return raw.charCodeAt(0) === 0xfeff ? raw.slice(1) : raw
}

/**
 * Replace content between a pair of sync marker HTML comments.
 * Returns the updated document string, or null if content is unchanged.
 */
function replaceBetweenMarkers(
  doc: string,
  marker: string,
  replacement: string,
): string | null {
  const startTag = `<!-- sync:${marker}:start -->`
  const endTag = `<!-- sync:${marker}:end -->`
  const startIdx = doc.indexOf(startTag)
  const endIdx = doc.indexOf(endTag)

  if (startIdx === -1 || endIdx === -1) {
    console.warn(`[sync] Warning: markers for '${marker}' not found, skipping`)
    return null
  }

  const before = doc.slice(0, startIdx + startTag.length)
  const after = doc.slice(endIdx)
  const newDoc = `${before}\n${replacement}\n${after}`

  // Return null when there is no actual change to avoid needless writes.
  return newDoc === doc ? null : newDoc
}

// ── Endpoint sync ─────────────────────────────────────────────────────────────
// relay.json → docs/api/overview.md

interface OpenAPIOperation {
  summary: string
  tags: string[]
  deprecated?: boolean
}

interface OpenAPISpec {
  paths: Record<string, Record<string, OpenAPIOperation>>
}

function syncEndpoints(): boolean {
  const specPath = resolve(ROOT, '..', '2b-svc-newapi', 'docs', 'openapi', 'relay.json')
  const docPath = resolve(DOCS, 'api', 'overview.md')

  let spec: OpenAPISpec
  try {
    spec = JSON.parse(readText(specPath))
  } catch (e) {
    console.warn(`[sync] Cannot read relay.json (${specPath}): ${(e as Error).message}`)
    return false
  }

  // Group implemented endpoints by their top-level tag.
  const groups = new Map<string, { method: string; path: string; summary: string }[]>()

  for (const [path, methods] of Object.entries(spec.paths)) {
    for (const [httpMethod, op] of Object.entries(methods)) {
      const tags: string[] = op.tags ?? []

      // Skip endpoints whose tags start with "未实现".
      if (tags.some(t => t.startsWith('未实现'))) continue

      // Use the first tag; take only the top-level group (before '/').
      const rawTag = tags[0] ?? '其他'
      const group = rawTag.split('/')[0]

      if (!groups.has(group)) groups.set(group, [])
      groups.get(group)!.push({
        method: httpMethod.toUpperCase(),
        path,
        summary: op.summary ?? '',
      })
    }
  }

  // Build markdown block with ApiEndpoint components.
  const lines: string[] = []
  for (const [group, endpoints] of groups) {
    lines.push(`**${group}**\n`)
    for (const ep of endpoints) {
      lines.push(
        `<ApiEndpoint method="${ep.method}" path="${ep.path}" description="${ep.summary}" />`,
      )
    }
    lines.push('')
  }

  const replacement = lines.join('\n').trimEnd()
  const doc = readText(docPath)
  const updated = replaceBetweenMarkers(doc, 'endpoints', replacement)
  if (updated === null) return false

  writeFileSync(docPath, updated, 'utf8')
  console.log('[sync] docs/api/overview.md updated (endpoints)')
  return true
}

// ── Model catalog sync ──────────────────────────────────────────────────────
// data/models.yaml → docs/.vitepress/data/model-catalog.ts
//
// The .data.ts loader convention only resolves `data` for a single owning
// page, so client components (e.g. ModelPicker) can't consume it. We emit a
// plain TS module they CAN import directly, keeping models.yaml canonical.

function syncModelCatalog(): boolean {
  const data = modelsLoader.load()
  const outPath = resolve(DOCS, '.vitepress', 'data', 'model-catalog.ts')

  const body = `// AUTO-GENERATED by scripts/sync.ts from data/models.yaml — DO NOT EDIT.
// Single source of truth: data/models.yaml. Run \`bun run sync\` to regenerate.
// Plain TS (not a .data.ts loader) so client components can import it directly.
export interface CatalogModel { id: string; context: string; price: string; status: string; tags: string[] }
export interface CatalogVendor { name: string; tagline?: string; models: CatalogModel[] }

export const modelCatalog: CatalogVendor[] = ${JSON.stringify(data.vendors, null, 2)}
`

  let existing = ''
  try {
    existing = readText(outPath)
  } catch {
    /* not generated yet */
  }
  if (existing === body) return false

  writeFileSync(outPath, body, 'utf8')
  console.log('[sync] docs/.vitepress/data/model-catalog.ts regenerated')
  return true
}

// ── Schema sync ───────────────────────────────────────────────────────────────
// relay.json components.schemas → docs/api/schemas.md
//
// Emits a property table per data structure that an implemented endpoint uses as
// a request/response body, plus the schemas those reference (BFS one level deep).

interface OASchemaNode {
  type?: string
  required?: string[]
  properties?: Record<string, OASchemaNode>
  description?: string
  items?: OASchemaNode
  $ref?: string
  oneOf?: OASchemaNode[]
  enum?: (string | number)[]
}

interface FullSpec {
  paths: Record<string, Record<string, OpenAPIOperation & {
    requestBody?: { content?: Record<string, { schema?: OASchemaNode }> }
    responses?: Record<string, { content?: Record<string, { schema?: OASchemaNode }> }>
  }>>
  components?: { schemas?: Record<string, OASchemaNode> }
}

const refName = (ref: string): string => ref.split('/').pop() ?? ref

/** Human-readable type label for a schema node (resolves $ref / array / oneOf / enum names). */
function typeLabel(v: OASchemaNode | undefined): string {
  if (!v) return '—'
  if (v.$ref) return refName(v.$ref)
  if (v.oneOf) return v.oneOf.map(typeLabel).join(' \\| ')
  if (v.type === 'array') return `array&lt;${v.items ? typeLabel(v.items) : 'any'}&gt;`
  let t = v.type ?? 'object'
  if (v.enum) t += ` (${v.enum.map(e => `\`${e}\``).join(' / ')})`
  return t
}

/** All schema names referenced (directly) by a node, for BFS expansion. */
function collectRefs(v: OASchemaNode | undefined): string[] {
  if (!v) return []
  if (v.$ref) return [refName(v.$ref)]
  if (v.items) return collectRefs(v.items)
  if (v.oneOf) return v.oneOf.flatMap(collectRefs)
  return []
}

function schemaTable(schema: OASchemaNode): string {
  const props = schema.properties ?? {}
  const required = new Set(schema.required ?? [])
  const rows = Object.entries(props).map(([k, v]) => {
    const t = typeLabel(v)
    const req = required.has(k) ? '是' : '—'
    const desc = (v.description ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ')
    return `| \`${k}\` | ${t} | ${req} | ${desc} |`
  })
  if (!rows.length) return '_（无字段定义）_'
  return `| 字段 | 类型 | 必填 | 说明 |\n|------|------|------|------|\n${rows.join('\n')}`
}

function syncSchemas(): boolean {
  const specPath = resolve(ROOT, '..', '2b-svc-newapi', 'docs', 'openapi', 'relay.json')
  const docPath = resolve(DOCS, 'api', 'schemas.md')

  let spec: FullSpec
  try {
    spec = JSON.parse(readText(specPath))
  } catch (e) {
    console.warn(`[sync] Cannot read relay.json for schemas: ${(e as Error).message}`)
    return false
  }

  const schemas = spec.components?.schemas ?? {}

  // Seed with request/response body schemas of implemented endpoints.
  const referenced = new Set<string>()
  for (const methods of Object.values(spec.paths)) {
    for (const op of Object.values(methods)) {
      if ((op.tags ?? []).some(t => t.startsWith('未实现'))) continue
      const rb = op.requestBody?.content?.['application/json']?.schema
      const resp = op.responses?.['200']?.content?.['application/json']?.schema
      for (const s of [rb, resp]) for (const r of collectRefs(s)) referenced.add(r)
    }
  }

  // BFS into nested property $refs so referenced sub-structures are documented too.
  const queue = [...referenced]
  while (queue.length) {
    const sc = schemas[queue.shift()!]
    if (!sc?.properties) continue
    for (const v of Object.values(sc.properties)) {
      for (const r of collectRefs(v)) if (!referenced.has(r)) { referenced.add(r); queue.push(r) }
    }
  }

  const blocks = [...referenced]
    .sort()
    .map(name => {
      const sc = schemas[name]
      if (!sc) return ''
      const desc = sc.description ? `${sc.description}\n\n` : ''
      return `<details class="lurus-faq-item">\n<summary><code>${name}</code></summary>\n\n${desc}${schemaTable(sc)}\n\n</details>`
    })
    .filter(Boolean)

  const replacement = `_共 ${blocks.length} 个数据结构（由 OpenAPI 规范自动生成）。_\n\n${blocks.join('\n\n')}`
  const doc = readText(docPath)
  const updated = replaceBetweenMarkers(doc, 'schemas', replacement)
  if (updated === null) return false

  writeFileSync(docPath, updated, 'utf8')
  console.log(`[sync] docs/api/schemas.md updated (${blocks.length} schemas)`)
  return true
}

// ── Main ──────────────────────────────────────────────────────────────────────

const changed = [syncEndpoints(), syncModelCatalog(), syncSchemas()].some(Boolean)
if (!changed) {
  console.log('[sync] All sources up-to-date, no changes written.')
} else {
  console.log('[sync] Sync complete.')
}
